<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gw_socket_close.proto

namespace GPBMetadata\Gateway;

class GwSocketClose
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad7010a1d676174657761792f67775f736f636b65745f636c6f73652e70" .
            "726f746f12076761746577617922290a144777536f636b6574436c6f7365" .
            "5265717565737412110a09736f636b657449647318012003280922170a15" .
            "4777536f636b6574436c6f7365526573706f6e736542610a16636f6d2e7a" .
            "616c792e70726f746f2e676174657761795a326769746875622e636f6d2f" .
            "6475636b636861742f6475636b636861742d676174657761792f70726f74" .
            "6f2f67617465776179ca02125a616c795c50726f746f5c47617465776179" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

