<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gw_socket_write.proto

namespace GPBMetadata\Gateway;

class GwSocketWrite
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac1020a1d676174657761792f67775f736f636b65745f77726974652e70" .
            "726f746f120767617465776179223a0a144777536f636b65745772697465" .
            "5061636b61676512110a09736f636b6574496473180120032809120f0a07" .
            "636f6e74656e7418022001280c22470a144777536f636b65745772697465" .
            "52657175657374122f0a087061636b6167657318012003280b321d2e6761" .
            "74657761792e4777536f636b657457726974655061636b61676522270a15" .
            "4777536f636b65745772697465526573706f6e7365120e0a066c656e6774" .
            "6818012001280542610a16636f6d2e7a616c792e70726f746f2e67617465" .
            "7761795a326769746875622e636f6d2f6475636b636861742f6475636b63" .
            "6861742d676174657761792f70726f746f2f67617465776179ca02125a61" .
            "6c795c50726f746f5c47617465776179620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

