<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/custom.proto

namespace GPBMetadata\Core;

class Custom
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a87030a11636f72652f637573746f6d2e70726f746f1204636f72652a4c" .
            "0a0a437573746f6d5479706512150a11437573746f6d54797065496e7661" .
            "6c6964100012130a0f437573746f6d547970654c6f67696e100112120a0e" .
            "437573746f6d547970655573657210022a480a0e437573746f6d44617461" .
            "5479706512130a0f4461746154797065496e76616c6964100012100a0c44" .
            "61746154797065546578741001120f0a0b4461746154797065496e741002" .
            "2a420a114c6f67696e437573746f6d53746174757312160a124c6f67696e" .
            "437573746f6d496e76616c6964100012150a114c6f67696e437573746f6d" .
            "4e6f726d616c10012a5f0a1055736572437573746f6d5374617475731215" .
            "0a1155736572437573746f6d496e76616c6964100012140a105573657243" .
            "7573746f6d4e6f726d616c1001121e0a1a55736572437573746f6d526567" .
            "69737465725265717569726564100242270a13636f6d2e7a616c792e7072" .
            "6f746f2e636f7265ca020f5a616c795c50726f746f5c436f726562067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

