<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_push_payload.proto

namespace GPBMetadata\Platform;

class ApiPushPayload
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Platform\Common::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0abc010a1f706c6174666f726d2f6170695f707573685f7061796c6f6164" .
            "2e70726f746f1208706c6174666f726d223c0a1541706950757368506179" .
            "6c6f61645265717565737412230a087061796c6f61647318012003280b32" .
            "112e706c6174666f726d2e5061796c6f616422180a164170695075736850" .
            "61796c6f6164526573706f6e7365422f0a17636f6d2e7a616c792e70726f" .
            "746f2e706c6174666f726dca02135a616c795c50726f746f5c506c617466" .
            "6f726d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

