<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_package_verify.proto

namespace GPBMetadata\Platform;

class ApiPackageVerify
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac7010a21706c6174666f726d2f6170695f7061636b6167655f76657269" .
            "66792e70726f746f1208706c6174666f726d22490a174170695061636b61" .
            "67655665726966795265717565737412130a0b7369676e41707053686131" .
            "18012001280912190a117061636b61676554696d65426173653634180220" .
            "012809222a0a184170695061636b616765566572696679526573706f6e73" .
            "65120e0a0676657269667918012001280842190a17636f6d2e7a616c792e" .
            "70726f746f2e706c6174666f726d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

