<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_push_cancel.proto

namespace GPBMetadata\Platform;

class ApiPushCancel
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af1010a1e706c6174666f726d2f6170695f707573685f63616e63656c2e" .
            "70726f746f1208706c6174666f726d22730a144170695075736843616e63" .
            "656c5265717565737412130a0b736974655075626b50656d180120012809" .
            "12150a0d6465766963655075626b50656d18022001280912180a1074696d" .
            "657374616d705365636f6e647318032001280912150a0d7369676e54696d" .
            "657374616d7018042001280922170a154170695075736843616e63656c52" .
            "6573706f6e7365422f0a17636f6d2e7a616c792e70726f746f2e706c6174" .
            "666f726dca02135a616c795c50726f746f5c506c6174666f726d62067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

