<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_platform_check.proto

namespace GPBMetadata\Platform;

class ApiPlatformCheck
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae2010a21706c6174666f726d2f6170695f706c6174666f726d5f636865" .
            "636b2e70726f746f1208706c6174666f726d22480a17417069506c617466" .
            "6f726d436865636b5265717565737412180a1070686f6e65436f756e7472" .
            "79436f646518012001280912130a0b70686f6e654e756d62657218022001" .
            "280922300a18417069506c6174666f726d436865636b526573706f6e7365" .
            "12140a0c6e6565645265676973746572180120012808422f0a17636f6d2e" .
            "7a616c792e70726f746f2e706c6174666f726dca02135a616c795c50726f" .
            "746f5c506c6174666f726d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

