<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_platform_login.proto

namespace GPBMetadata\Platform;

class ApiPlatformLogin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abd020a21706c6174666f726d2f6170695f706c6174666f726d5f6c6f67" .
            "696e2e70726f746f1208706c6174666f726d228f010a17417069506c6174" .
            "666f726d4c6f67696e5265717565737412180a1070686f6e65436f756e74" .
            "7279436f646518012001280912130a0b70686f6e654e756d626572180220" .
            "01280912120a0a766572696679436f646518032001280912130a0b736974" .
            "655075626b50656d180420012809121c0a146c6f67696e4e616d65466f72" .
            "526567697374657218052001280922430a18417069506c6174666f726d4c" .
            "6f67696e526573706f6e736512140a0c70726553657373696f6e49641801" .
            "2001280912110a096c6f67696e4e616d65180220012809422f0a17636f6d" .
            "2e7a616c792e70726f746f2e706c6174666f726dca02135a616c795c5072" .
            "6f746f5c506c6174666f726d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

