<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_push_check.proto

namespace GPBMetadata\Platform;

class ApiPushCheck
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ace010a1d706c6174666f726d2f6170695f707573685f636865636b2e70" .
            "726f746f1208706c6174666f726d22400a1341706950757368436865636b" .
            "5265717565737412120a0a736974655075626b496418012001280912150a" .
            "0d7369746555736572546f6b656e18022001280922280a14417069507573" .
            "68436865636b526573706f6e736512100a08707573684d61726b18012001" .
            "2809422f0a17636f6d2e7a616c792e70726f746f2e706c6174666f726dca" .
            "02135a616c795c50726f746f5c506c6174666f726d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

