<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_push_notification.proto

namespace GPBMetadata\Platform;

class ApiPushNotification
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Platform\Common::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af6010a24706c6174666f726d2f6170695f707573685f6e6f7469666963" .
            "6174696f6e2e70726f746f1208706c6174666f726d226c0a1a4170695075" .
            "73684e6f74696669636174696f6e5265717565737412280a0a7075736848" .
            "656164657218012001280b32142e706c6174666f726d2e50757368486561" .
            "64657212240a0870757368426f647918022001280b32122e706c6174666f" .
            "726d2e50757368426f6479221d0a1b417069507573684e6f746966696361" .
            "74696f6e526573706f6e7365422f0a17636f6d2e7a616c792e70726f746f" .
            "2e706c6174666f726dca02135a616c795c50726f746f5c506c6174666f72" .
            "6d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

