<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_session_verify.proto

namespace GPBMetadata\Platform;

class ApiSessionVerify
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ada010a21706c6174666f726d2f6170695f73657373696f6e5f76657269" .
            "66792e70726f746f1208706c6174666f726d222f0a174170695365737369" .
            "6f6e5665726966795265717565737412140a0c70726553657373696f6e49" .
            "6418012001280922410a1841706953657373696f6e566572696679526573" .
            "706f6e7365120b0a036b657918012001280c12180a10656e637279707465" .
            "6450726f66696c6518022001280c422f0a17636f6d2e7a616c792e70726f" .
            "746f2e706c6174666f726dca02135a616c795c50726f746f5c506c617466" .
            "6f726d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

