<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_session_login.proto

namespace GPBMetadata\Platform;

class ApiSessionLogin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0afe010a20706c6174666f726d2f6170695f73657373696f6e5f6c6f6769" .
            "6e2e70726f746f1208706c6174666f726d22660a1641706953657373696f" .
            "6e4c6f67696e5265717565737412160a0e696e7669746174696f6e436f64" .
            "65180120012809121a0a12616c6c6f7753686172655265616c6e616d6518" .
            "022001280812180a107369746549645075626b4261736536341803200128" .
            "09222f0a1741706953657373696f6e4c6f67696e526573706f6e73651214" .
            "0a0c70726553657373696f6e4964180120012809422f0a17636f6d2e7a61" .
            "6c792e70726f746f2e706c6174666f726dca02135a616c795c50726f746f" .
            "5c506c6174666f726d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

