<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_site_register.proto

namespace GPBMetadata\Platform;

class ApiSiteRegister
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9e020a20706c6174666f726d2f6170695f736974655f72656769737465" .
            "722e70726f746f1208706c6174666f726d22730a16417069536974655265" .
            "6769737465725265717565737412100a086e69636b6e616d651801200128" .
            "0912160a0e696e7669746174696f6e436f6465180220012809121a0a1261" .
            "6c6c6f7753686172655265616c6e616d6518032001280812130a0b736974" .
            "655075626b50656d18042001280922420a17417069536974655265676973" .
            "746572526573706f6e736512140a0c70726553657373696f6e4964180120" .
            "01280912110a096c6f67696e4e616d65180220012809422f0a17636f6d2e" .
            "7a616c792e70726f746f2e706c6174666f726dca02135a616c795c50726f" .
            "746f5c506c6174666f726d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

