<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_sms_verifyCode.proto

namespace GPBMetadata\Platform;

class ApiSmsVerifyCode
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab8020a21706c6174666f726d2f6170695f736d735f766572696679436f" .
            "64652e70726f746f1208706c6174666f726d22700a144170695665726966" .
            "79436f64655265717565737412180a1070686f6e65436f756e747279436f" .
            "646518012001280912130a0b70686f6e654e756d62657218022001280912" .
            "290a047479706518032001280e321b2e706c6174666f726d2e536d735665" .
            "72696679436f64655479706522170a15417069566572696679436f646552" .
            "6573706f6e73652a450a11536d73566572696679436f6465547970651218" .
            "0a14536d73566572696679436f6465496e76616c6964100012160a12536d" .
            "73566572696679436f64654c6f67696e1001422f0a17636f6d2e7a616c79" .
            "2e70726f746f2e706c6174666f726dca02135a616c795c50726f746f5c50" .
            "6c6174666f726d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

