<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_site_mute.proto

namespace GPBMetadata\Platform;

class ApiSiteMute
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac4010a1c706c6174666f726d2f6170695f736974655f6d7574652e7072" .
            "6f746f1208706c6174666f726d224a0a12417069536974654d7574655265" .
            "717565737412100a0873697465436f646518012001280912120a0a736974" .
            "65557365724964180220012809120e0a0669734d75746518032001280822" .
            "150a13417069536974654d757465526573706f6e7365422f0a17636f6d2e" .
            "7a616c792e70726f746f2e706c6174666f726dca02135a616c795c50726f" .
            "746f5c506c6174666f726d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

