<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/core.proto

namespace GPBMetadata\Platform;

class Core
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae9010a13706c6174666f726d2f636f72652e70726f746f1208706c6174" .
            "666f726d228e010a104c6f67696e5573657250726f66696c65120e0a0675" .
            "736572496418012001280912110a096c6f67696e4e616d65180220012809" .
            "12100a086e69636b4e616d6518032001280912180a1070686f6e65436f75" .
            "6e747279436f646518042001280912130a0b70686f6e654e756d62657218" .
            "052001280912160a0e696e7669746174696f6e436f646518062001280942" .
            "2f0a17636f6d2e7a616c792e70726f746f2e706c6174666f726dca02135a" .
            "616c795c50726f746f5c506c6174666f726d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

