<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/duckchat_site_admins.proto

namespace Zaly\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plugin.DuckChatSiteAdminsResponse</code>
 */
class DuckChatSiteAdminsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .core.PublicUserProfile publicProfiles = 1;</code>
     */
    private $publicProfiles;

    public function __construct() {
        \GPBMetadata\Plugin\DuckchatSiteAdmins::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .core.PublicUserProfile publicProfiles = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPublicProfiles()
    {
        return $this->publicProfiles;
    }

    /**
     * Generated from protobuf field <code>repeated .core.PublicUserProfile publicProfiles = 1;</code>
     * @param \Zaly\Proto\Core\PublicUserProfile[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPublicProfiles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zaly\Proto\Core\PublicUserProfile::class);
        $this->publicProfiles = $arr;

        return $this;
    }

}

