<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/duckchat_site_admins.proto

namespace Zaly\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action = duckchat.site.admins
 *
 * Generated from protobuf message <code>plugin.DuckChatSiteAdminsRequest</code>
 */
class DuckChatSiteAdminsRequest extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Plugin\DuckchatSiteAdmins::initOnce();
        parent::__construct();
    }

}

