<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/duckchat_session_clear.proto

namespace Zaly\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plugin.DuckChatSessionClearResponse</code>
 */
class DuckChatSessionClearResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Plugin\DuckchatSessionClear::initOnce();
        parent::__construct();
    }

}

