<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/duckchat_message_send.proto

namespace Zaly\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *what
 *
 * Generated from protobuf message <code>plugin.DuckChatMessageSendResponse</code>
 */
class DuckChatMessageSendResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Plugin\DuckchatMessageSend::initOnce();
        parent::__construct();
    }

}

