<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/duckchat_user_profile.proto

namespace Zaly\Proto\Plugin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: duckchat.user.profile
 *
 * Generated from protobuf message <code>plugin.DuckChatUserProfileRequest</code>
 */
class DuckChatUserProfileRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *get userId’s
     *
     * Generated from protobuf field <code>string userId = 1;</code>
     */
    private $userId = '';

    public function __construct() {
        \GPBMetadata\Plugin\DuckchatUserProfile::initOnce();
        parent::__construct();
    }

    /**
     *get userId’s
     *
     * Generated from protobuf field <code>string userId = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     *get userId’s
     *
     * Generated from protobuf field <code>string userId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->userId = $var;

        return $this;
    }

}

