<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_friend_list.proto

namespace GPBMetadata\Site;

class ApiFriendList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a92020a1a736974652f6170695f667269656e645f6c6973742e70726f74" .
            "6f12047369746522350a14417069467269656e644c697374526571756573" .
            "74120e0a066f6666736574180120012805120d0a05636f756e7418022001" .
            "280522550a15417069467269656e644c697374526573706f6e736512280a" .
            "07667269656e647318012003280b32172e636f72652e467269656e645573" .
            "657250726f66696c6512120a0a746f74616c436f756e7418022001280542" .
            "580a13636f6d2e7a616c792e70726f746f2e736974655a2f676974687562" .
            "2e636f6d2f6475636b636861742f6475636b636861742d67617465776179" .
            "2f70726f746f2f73697465ca020f5a616c795c50726f746f5c5369746562" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

