<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_friend_delete.proto

namespace GPBMetadata\Site;

class ApiFriendDelete
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0acd010a1c736974652f6170695f667269656e645f64656c6574652e7072" .
            "6f746f120473697465222a0a16417069467269656e6444656c6574655265" .
            "717565737412100a08746f55736572496418012001280922190a17417069" .
            "467269656e6444656c657465526573706f6e736542580a13636f6d2e7a61" .
            "6c792e70726f746f2e736974655a2f6769746875622e636f6d2f6475636b" .
            "636861742f6475636b636861742d676174657761792f70726f746f2f7369" .
            "7465ca020f5a616c795c50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

