<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_friend_accept.proto

namespace GPBMetadata\Site;

class ApiFriendAccept
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0adf010a1c736974652f6170695f667269656e645f6163636570742e7072" .
            "6f746f120473697465223c0a16417069467269656e644163636570745265" .
            "717565737412130a0b6170706c79557365724964180120012809120d0a05" .
            "616772656518022001280822190a17417069467269656e64416363657074" .
            "526573706f6e736542580a13636f6d2e7a616c792e70726f746f2e736974" .
            "655a2f6769746875622e636f6d2f6475636b636861742f6475636b636861" .
            "742d676174657761792f70726f746f2f73697465ca020f5a616c795c5072" .
            "6f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

