<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_file_download.proto

namespace GPBMetadata\Site;

class ApiFileDownload
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ace020a1c736974652f6170695f66696c655f646f776e6c6f61642e7072" .
            "6f746f12047369746522690a1641706946696c65446f776e6c6f61645265" .
            "7175657374120e0a0666696c65496418012001280912140a0c7265747572" .
            "6e42617365363418022001280812110a096d657373616765496418032001" .
            "280912160a0e697347726f75704d657373616765180420012808225b0a17" .
            "41706946696c65446f776e6c6f6164526573706f6e7365120e0a0466696c" .
            "6518012001280c480012140a0a66696c6542617365363418022001280948" .
            "0012130a0b636f6e74656e745479706518032001280942050a0372657442" .
            "580a13636f6d2e7a616c792e70726f746f2e736974655a2f676974687562" .
            "2e636f6d2f6475636b636861742f6475636b636861742d67617465776179" .
            "2f70726f746f2f73697465ca020f5a616c795c50726f746f5c5369746562" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

