<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_friend_apply.proto

namespace GPBMetadata\Site;

class ApiFriendApply
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0add010a1b736974652f6170695f667269656e645f6170706c792e70726f" .
            "746f120473697465223c0a15417069467269656e644170706c7952657175" .
            "65737412100a08746f55736572496418012001280912110a096772656574" .
            "696e677318022001280922180a16417069467269656e644170706c795265" .
            "73706f6e736542580a13636f6d2e7a616c792e70726f746f2e736974655a" .
            "2f6769746875622e636f6d2f6475636b636861742f6475636b636861742d" .
            "676174657761792f70726f746f2f73697465ca020f5a616c795c50726f74" .
            "6f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

