<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_file_upload.proto

namespace GPBMetadata\Site;

class ApiFileUpload
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Net::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a92020a1a736974652f6170695f66696c655f75706c6f61642e70726f74" .
            "6f12047369746522630a1441706946696c6555706c6f6164526571756573" .
            "74120c0a0466696c6518012001280c12200a0866696c6554797065180220" .
            "01280e320e2e636f72652e46696c6554797065121b0a1369734d65737361" .
            "67654174746163686d656e7418032001280822270a1541706946696c6555" .
            "706c6f6164526573706f6e7365120e0a0666696c65496418012001280942" .
            "580a13636f6d2e7a616c792e70726f746f2e736974655a2f676974687562" .
            "2e636f6d2f6475636b636861742f6475636b636861742d67617465776179" .
            "2f70726f746f2f73697465ca020f5a616c795c50726f746f5c5369746562" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

