<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_friend_applyList.proto

namespace GPBMetadata\Site;

class ApiFriendApplyList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9d020a1f736974652f6170695f667269656e645f6170706c794c697374" .
            "2e70726f746f120473697465223a0a19417069467269656e644170706c79" .
            "4c69737452657175657374120e0a066f6666736574180120012805120d0a" .
            "05636f756e7418022001280522560a1a417069467269656e644170706c79" .
            "4c697374526573706f6e736512240a046c69737418012003280b32162e63" .
            "6f72652e4170706c795573657250726f66696c6512120a0a746f74616c43" .
            "6f756e7418022001280542580a13636f6d2e7a616c792e70726f746f2e73" .
            "6974655a2f6769746875622e636f6d2f6475636b636861742f6475636b63" .
            "6861742d676174657761792f70726f746f2f73697465ca020f5a616c795c" .
            "50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

