<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_friend_profile.proto

namespace GPBMetadata\Site;

class ApiFriendProfile
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af8010a1d736974652f6170695f667269656e645f70726f66696c652e70" .
            "726f746f12047369746522290a17417069467269656e6450726f66696c65" .
            "52657175657374120e0a0675736572496418012001280922440a18417069" .
            "467269656e6450726f66696c65526573706f6e736512280a0770726f6669" .
            "6c6518012001280b32172e636f72652e467269656e645573657250726f66" .
            "696c6542580a13636f6d2e7a616c792e70726f746f2e736974655a2f6769" .
            "746875622e636f6d2f6475636b636861742f6475636b636861742d676174" .
            "657761792f70726f746f2f73697465ca020f5a616c795c50726f746f5c53" .
            "697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

