<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_friend_search.proto

namespace GPBMetadata\Site;

class ApiFriendSearch
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aaa020a1c736974652f6170695f667269656e645f7365617263682e7072" .
            "6f746f12047369746522490a16417069467269656e645365617263685265" .
            "717565737412100a086b6579776f726473180120012809120e0a066f6666" .
            "736574180220012805120d0a05636f756e7418032001280522570a174170" .
            "69467269656e64536561726368526573706f6e736512280a07667269656e" .
            "647318012003280b32172e636f72652e467269656e645573657250726f66" .
            "696c6512120a0a746f74616c436f756e7418022001280542580a13636f6d" .
            "2e7a616c792e70726f746f2e736974655a2f6769746875622e636f6d2f64" .
            "75636b636861742f6475636b636861742d676174657761792f70726f746f" .
            "2f73697465ca020f5a616c795c50726f746f5c53697465620670726f746f" .
            "33"
        ));

        static::$is_initialized = true;
    }
}

