<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_group_removeMember.proto

namespace GPBMetadata\Site;

class ApiGroupRemoveMember
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aec010a21736974652f6170695f67726f75705f72656d6f76654d656d62" .
            "65722e70726f746f120473697465223f0a1b41706947726f757052656d6f" .
            "76654d656d62657252657175657374120f0a0767726f7570496418012001" .
            "2809120f0a0775736572496473180220032809221e0a1c41706947726f75" .
            "7052656d6f76654d656d626572526573706f6e736542580a13636f6d2e7a" .
            "616c792e70726f746f2e736974655a2f6769746875622e636f6d2f647563" .
            "6b636861742f6475636b636861742d676174657761792f70726f746f2f73" .
            "697465ca020f5a616c795c50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

