<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_group_setSpeaker.proto

namespace GPBMetadata\Site;

class ApiGroupSetSpeaker
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af3020a1f736974652f6170695f67726f75705f736574537065616b6572" .
            "2e70726f746f120473697465226b0a1941706947726f7570536574537065" .
            "616b657252657175657374120f0a0767726f757049641801200128091225" .
            "0a077365745479706518022001280e32142e736974652e53657453706561" .
            "6b65725479706512160a0e737065616b6572557365724964731803200328" .
            "0922340a1a41706947726f7570536574537065616b6572526573706f6e73" .
            "6512160a0e737065616b6572557365724964731801200328092a450a0e53" .
            "6574537065616b657254797065120e0a0a416464537065616b6572100012" .
            "110a0d52656d6f7665537065616b6572100112100a0c436c6f7365537065" .
            "616b6572100242580a13636f6d2e7a616c792e70726f746f2e736974655a" .
            "2f6769746875622e636f6d2f6475636b636861742f6475636b636861742d" .
            "676174657761792f70726f746f2f73697465ca020f5a616c795c50726f74" .
            "6f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

