<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_group_quit.proto

namespace GPBMetadata\Site;

class ApiGroupQuit
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac3010a19736974652f6170695f67726f75705f717569742e70726f746f" .
            "12047369746522260a1341706947726f7570517569745265717565737412" .
            "0f0a0767726f7570496418012001280922160a1441706947726f75705175" .
            "6974526573706f6e736542580a13636f6d2e7a616c792e70726f746f2e73" .
            "6974655a2f6769746875622e636f6d2f6475636b636861742f6475636b63" .
            "6861742d676174657761792f70726f746f2f73697465ca020f5a616c795c" .
            "50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

