<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_group_members.proto

namespace GPBMetadata\Site;

class ApiGroupMembers
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Group::initOnce();
        \GPBMetadata\Core\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aad030a1c736974652f6170695f67726f75705f6d656d626572732e7072" .
            "6f746f1204736974651a0f636f72652f757365722e70726f746f226b0a1a" .
            "41706947726f75704d656d626572735573657250726f66696c6512280a07" .
            "70726f66696c6518012001280b32172e636f72652e5075626c6963557365" .
            "7250726f66696c6512230a047479706518022001280e32152e636f72652e" .
            "47726f75704d656d6265725479706522480a1641706947726f75704d656d" .
            "6265727352657175657374120f0a0767726f75704964180120012809120e" .
            "0a066f6666736574180220012805120d0a05636f756e7418032001280522" .
            "5d0a1741706947726f75704d656d62657273526573706f6e7365122e0a04" .
            "6c69737418012003280b32202e736974652e41706947726f75704d656d62" .
            "6572735573657250726f66696c6512120a0a746f74616c436f756e741802" .
            "2001280542580a13636f6d2e7a616c792e70726f746f2e736974655a2f67" .
            "69746875622e636f6d2f6475636b636861742f6475636b636861742d6761" .
            "74657761792f70726f746f2f73697465ca020f5a616c795c50726f746f5c" .
            "53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

