<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_gw_onDisconnect.proto

namespace GPBMetadata\Site;

class ApiGwOnDisconnect
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad3010a1e736974652f6170695f67775f6f6e446973636f6e6e6563742e" .
            "70726f746f120473697465222c0a1841706947774f6e446973636f6e6e65" .
            "63745265717565737412100a08736f636b65744964180120012809221b0a" .
            "1941706947774f6e446973636f6e6e656374526573706f6e736542580a13" .
            "636f6d2e7a616c792e70726f746f2e736974655a2f6769746875622e636f" .
            "6d2f6475636b636861742f6475636b636861742d676174657761792f7072" .
            "6f746f2f73697465ca020f5a616c795c50726f746f5c5369746562067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

