<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_gw_config.proto

namespace GPBMetadata\Site;

class ApiGwConfig
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Net::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af4010a18736974652f6170695f67775f636f6e6669672e70726f746f12" .
            "047369746522430a124170694777436f6e66696752657175657374121f0a" .
            "047479706518012001280e32112e636f72652e4761746577617954797065" .
            "120c0a04686f7374180220012809222b0a134170694777436f6e66696752" .
            "6573706f6e736512140a0c736f636b6574496453616c7418012001280942" .
            "580a13636f6d2e7a616c792e70726f746f2e736974655a2f676974687562" .
            "2e636f6d2f6475636b636861742f6475636b636861742d67617465776179" .
            "2f70726f746f2f73697465ca020f5a616c795c50726f746f5c5369746562" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

