<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_group_list.proto

namespace GPBMetadata\Site;

class ApiGroupList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Group::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a81030a19736974652f6170695f67726f75705f6c6973742e70726f746f" .
            "12047369746522340a1341706947726f75704c6973745265717565737412" .
            "0e0a066f6666736574180120012805120d0a05636f756e74180220012805" .
            "22c5010a1441706947726f75704c697374526573706f6e736512260a046c" .
            "69737418012003280b32182e636f72652e5075626c696347726f75705072" .
            "6f66696c65123e0a0a6c69737449734d75746518022003280b322a2e7369" .
            "74652e41706947726f75704c697374526573706f6e73652e4c6973744973" .
            "4d757465456e74727912120a0a746f74616c436f756e741803200128051a" .
            "310a0f4c69737449734d757465456e747279120b0a036b65791801200128" .
            "09120d0a0576616c75651802200128083a02380142580a13636f6d2e7a61" .
            "6c792e70726f746f2e736974655a2f6769746875622e636f6d2f6475636b" .
            "636861742f6475636b636861742d676174657761792f70726f746f2f7369" .
            "7465ca020f5a616c795c50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

