<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_group_report.proto

namespace GPBMetadata\Site;

class ApiGroupReport
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aeb010a1b736974652f6170695f67726f75705f7265706f72742e70726f" .
            "746f120473697465224a0a1541706947726f75705265706f727452657175" .
            "657374120f0a0767726f7570496418012001280912120a0a7265706f7274" .
            "54797065180220012805120c0a046e6f746518032001280922180a164170" .
            "6947726f75705265706f7274526573706f6e736542580a13636f6d2e7a61" .
            "6c792e70726f746f2e736974655a2f6769746875622e636f6d2f6475636b" .
            "636861742f6475636b636861742d676174657761792f70726f746f2f7369" .
            "7465ca020f5a616c795c50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

