<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_group_invite.proto

namespace GPBMetadata\Site;

class ApiGroupInvite
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ada010a1b736974652f6170695f67726f75705f696e766974652e70726f" .
            "746f12047369746522390a1541706947726f7570496e7669746552657175" .
            "657374120f0a0767726f75704964180120012809120f0a07757365724964" .
            "7318022003280922180a1641706947726f7570496e76697465526573706f" .
            "6e736542580a13636f6d2e7a616c792e70726f746f2e736974655a2f6769" .
            "746875622e636f6d2f6475636b636861742f6475636b636861742d676174" .
            "657761792f70726f746f2f73697465ca020f5a616c795c50726f746f5c53" .
            "697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

