<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_group_delete.proto

namespace GPBMetadata\Site;

class ApiGroupDelete
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac9010a1b736974652f6170695f67726f75705f64656c6574652e70726f" .
            "746f12047369746522280a1541706947726f757044656c65746552657175" .
            "657374120f0a0767726f7570496418012001280922180a1641706947726f" .
            "757044656c657465526573706f6e736542580a13636f6d2e7a616c792e70" .
            "726f746f2e736974655a2f6769746875622e636f6d2f6475636b63686174" .
            "2f6475636b636861742d676174657761792f70726f746f2f73697465ca02" .
            "0f5a616c795c50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

