<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_message_checkStatus.proto

namespace GPBMetadata\Site;

class ApiMessageCheckStatus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Message::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab3020a22736974652f6170695f6d6573736167655f636865636b537461" .
            "7475732e70726f746f12047369746522570a1c4170694d65737361676543" .
            "6865636b53746174757352657175657374120e0a066d7367496473180120" .
            "03280912270a08726f6f6d5479706518022001280e32152e636f72652e4d" .
            "657373616765526f6f6d54797065224c0a1d4170694d6573736167654368" .
            "65636b537461747573526573706f6e7365122b0a0e7374617475734d6573" .
            "736167657318012003280b32132e636f72652e5374617475734d65737361" .
            "676542580a13636f6d2e7a616c792e70726f746f2e736974655a2f676974" .
            "6875622e636f6d2f6475636b636861742f6475636b636861742d67617465" .
            "7761792f70726f746f2f73697465ca020f5a616c795c50726f746f5c5369" .
            "7465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

