<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_passport_ldap_login.proto

namespace GPBMetadata\Site;

class ApiPassportLdapLogin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a84020a22736974652f6170695f70617373706f72745f6c6461705f6c6f" .
            "67696e2e70726f746f12047369746522400a1b41706950617373706f7274" .
            "4c6461704c6f67696e52657175657374120f0a076163636f756e74180120" .
            "01280912100a0870617373776f726418022001280922340a1c4170695061" .
            "7373706f72744c6461704c6f67696e526573706f6e736512140a0c707265" .
            "53657373696f6e496418012001280942580a13636f6d2e7a616c792e7072" .
            "6f746f2e736974655a2f6769746875622e636f6d2f6475636b636861742f" .
            "6475636b636861742d676174657761792f70726f746f2f73697465ca020f" .
            "5a616c795c50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

