<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_passport_password_modifyPassword.proto

namespace GPBMetadata\Site;

class ApiPassportPasswordModifyPassword
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aac020a2f736974652f6170695f70617373706f72745f70617373776f72" .
            "645f6d6f6469667950617373776f72642e70726f746f1204736974652264" .
            "0a2841706950617373706f727450617373776f72644d6f64696679506173" .
            "73776f72645265717565737412110a096c6f67696e4e616d651801200128" .
            "0912100a0870617373776f726418022001280912130a0b6e657750617373" .
            "776f7264180320012809222b0a2941706950617373706f72745061737377" .
            "6f72644d6f6469667950617373776f7264526573706f6e736542580a1363" .
            "6f6d2e7a616c792e70726f746f2e736974655a2f6769746875622e636f6d" .
            "2f6475636b636861742f6475636b636861742d676174657761792f70726f" .
            "746f2f73697465ca020f5a616c795c50726f746f5c53697465620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

