<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_passport_password_updateInvitationCode.proto

namespace GPBMetadata\Site;

class ApiPassportPasswordUpdateInvitationCode
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0add020a35736974652f6170695f70617373706f72745f70617373776f72" .
            "645f757064617465496e7669746174696f6e436f64652e70726f746f1204" .
            "7369746522730a2e41706950617373706f727450617373776f7264557064" .
            "617465496e7669746174696f6e436f64655265717565737412130a0b7369" .
            "74655075626b50656d18012001280912160a0e696e7669746174696f6e43" .
            "6f646518022001280912140a0c70726553657373696f6e49641803200128" .
            "0922470a2f41706950617373706f727450617373776f7264557064617465" .
            "496e7669746174696f6e436f6465526573706f6e736512140a0c70726553" .
            "657373696f6e496418012001280942580a13636f6d2e7a616c792e70726f" .
            "746f2e736974655a2f6769746875622e636f6d2f6475636b636861742f64" .
            "75636b636861742d676174657761792f70726f746f2f73697465ca020f5a" .
            "616c795c50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

