<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_passport_password_reg.proto

namespace GPBMetadata\Site;

class ApiPassportPasswordReg
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0adb020a24736974652f6170695f70617373706f72745f70617373776f72" .
            "645f7265672e70726f746f1204736974652292010a1d4170695061737370" .
            "6f727450617373776f72645265675265717565737412110a096c6f67696e" .
            "4e616d6518012001280912100a0870617373776f7264180220012809120d" .
            "0a05656d61696c18032001280912100a086e69636b6e616d651804200128" .
            "0912130a0b736974655075626b50656d18052001280912160a0e696e7669" .
            "746174696f6e436f646518062001280922360a1e41706950617373706f72" .
            "7450617373776f7264526567526573706f6e736512140a0c707265536573" .
            "73696f6e496418012001280942580a13636f6d2e7a616c792e70726f746f" .
            "2e736974655a2f6769746875622e636f6d2f6475636b636861742f647563" .
            "6b636861742d676174657761792f70726f746f2f73697465ca020f5a616c" .
            "795c50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

