<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_passport_password_login.proto

namespace GPBMetadata\Site;

class ApiPassportPasswordLogin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa7020a26736974652f6170695f70617373706f72745f70617373776f72" .
            "645f6c6f67696e2e70726f746f120473697465225b0a1f41706950617373" .
            "706f727450617373776f72644c6f67696e5265717565737412110a096c6f" .
            "67696e4e616d6518012001280912100a0870617373776f72641802200128" .
            "0912130a0b736974655075626b50656d18032001280922380a2041706950" .
            "617373706f727450617373776f72644c6f67696e526573706f6e73651214" .
            "0a0c70726553657373696f6e496418012001280942580a13636f6d2e7a61" .
            "6c792e70726f746f2e736974655a2f6769746875622e636f6d2f6475636b" .
            "636861742f6475636b636861742d676174657761792f70726f746f2f7369" .
            "7465ca020f5a616c795c50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

