<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_passport_anonymous_login.proto

namespace GPBMetadata\Site;

class ApiPassportAnonymousLogin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a83020a27736974652f6170695f70617373706f72745f616e6f6e796d6f" .
            "75735f6c6f67696e2e70726f746f12047369746522350a20417069506173" .
            "73706f7274416e6f6e796d6f75734c6f67696e5265717565737412110a09" .
            "6c6f67696e4e616d6518012001280922390a2141706950617373706f7274" .
            "416e6f6e796d6f75734c6f67696e526573706f6e736512140a0c70726553" .
            "657373696f6e496418012001280942580a13636f6d2e7a616c792e70726f" .
            "746f2e736974655a2f6769746875622e636f6d2f6475636b636861742f64" .
            "75636b636861742d676174657761792f70726f746f2f73697465ca020f5a" .
            "616c795c50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

