<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_passport_password_findPassword.proto

namespace GPBMetadata\Site;

class ApiPassportPasswordFindPassword
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aff010a2d736974652f6170695f70617373706f72745f70617373776f72" .
            "645f66696e6450617373776f72642e70726f746f120473697465223b0a26" .
            "41706950617373706f727450617373776f726446696e6450617373776f72" .
            "645265717565737412110a096c6f67696e4e616d6518012001280922290a" .
            "2741706950617373706f727450617373776f726446696e6450617373776f" .
            "7264526573706f6e736542580a13636f6d2e7a616c792e70726f746f2e73" .
            "6974655a2f6769746875622e636f6d2f6475636b636861742f6475636b63" .
            "6861742d676174657761792f70726f746f2f73697465ca020f5a616c795c" .
            "50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

