<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_passport_password_resetPassword.proto

namespace GPBMetadata\Site;

class ApiPassportPasswordResetPassword
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa3020a2e736974652f6170695f70617373706f72745f70617373776f72" .
            "645f726573657450617373776f72642e70726f746f120473697465225d0a" .
            "2741706950617373706f727450617373776f726452657365745061737377" .
            "6f72645265717565737412110a096c6f67696e4e616d6518012001280912" .
            "0d0a05746f6b656e18022001280912100a0870617373776f726418032001" .
            "2809222a0a2841706950617373706f727450617373776f72645265736574" .
            "50617373776f7264526573706f6e736542580a13636f6d2e7a616c792e70" .
            "726f746f2e736974655a2f6769746875622e636f6d2f6475636b63686174" .
            "2f6475636b636861742d676174657761792f70726f746f2f73697465ca02" .
            "0f5a616c795c50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

