<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_sync_check.proto

namespace GPBMetadata\Site;

class ApiSyncCheck
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab4020a19736974652f6170695f73796e635f636865636b2e70726f746f" .
            "120473697465224c0a1341706953796e63436865636b5265717565737412" .
            "1f0a047479706518012001280e32112e736974652e41706953796e635479" .
            "706512140a0c6c6f63616c56657273696f6e18022001280522270a144170" .
            "6953796e63436865636b526573706f6e7365120f0a0776657273696f6e18" .
            "01200128052a380a0b41706953796e635479706512120a0e41706953796e" .
            "63496e76616c6964100012150a1141706953796e63467269656e644c6973" .
            "74100142580a13636f6d2e7a616c792e70726f746f2e736974655a2f6769" .
            "746875622e636f6d2f6475636b636861742f6475636b636861742d676174" .
            "657761792f70726f746f2f73697465ca020f5a616c795c50726f746f5c53" .
            "697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

