<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_site_logout.proto

namespace GPBMetadata\Site;

class ApiSiteLogout
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab5010a1a736974652f6170695f736974655f6c6f676f75742e70726f74" .
            "6f12047369746522160a14417069536974654c6f676f7574526571756573" .
            "7422170a15417069536974654c6f676f7574526573706f6e736542580a13" .
            "636f6d2e7a616c792e70726f746f2e736974655a2f6769746875622e636f" .
            "6d2f6475636b636861742f6475636b636861742d676174657761792f7072" .
            "6f746f2f73697465ca020f5a616c795c50726f746f5c5369746562067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

