<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_site_config.proto

namespace GPBMetadata\Site;

class ApiSiteConfig
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Site::initOnce();
        \GPBMetadata\Core\Plugin::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae4020a1a736974652f6170695f736974655f636f6e6669672e70726f74" .
            "6f1204736974651a11636f72652f706c7567696e2e70726f746f22260a14" .
            "41706953697465436f6e66696752657175657374120e0a0672616e646f6d" .
            "18012001280922a2010a1541706953697465436f6e666967526573706f6e" .
            "736512260a06636f6e66696718012001280b32162e636f72652e5075626c" .
            "696353697465436f6e66696712180a1072616e646f6d5369676e42617365" .
            "363418022001280912160a0e697353657373696f6e56616c696418032001" .
            "2808122f0a126c6f67696e506c7567696e50726f66696c6518042001280b" .
            "32132e636f72652e506c7567696e50726f66696c6542580a13636f6d2e7a" .
            "616c792e70726f746f2e736974655a2f6769746875622e636f6d2f647563" .
            "6b636861742f6475636b636861742d676174657761792f70726f746f2f73" .
            "697465ca020f5a616c795c50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

