<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_tmpchat_group.proto

namespace GPBMetadata\Site;

class ApiTmpchatGroup
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ade010a1c736974652f6170695f746d70636861745f67726f75702e7072" .
            "6f746f120473697465223b0a16417069546d706368617447726f75705265" .
            "7175657374120f0a0767726f7570496418012001280912100a08746f5573" .
            "6572496418022001280922190a17417069546d706368617447726f757052" .
            "6573706f6e736542580a13636f6d2e7a616c792e70726f746f2e73697465" .
            "5a2f6769746875622e636f6d2f6475636b636861742f6475636b63686174" .
            "2d676174657761792f70726f746f2f73697465ca020f5a616c795c50726f" .
            "746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

