<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_tmpchat_delete.proto

namespace GPBMetadata\Site;

class ApiTmpchatDelete
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad0010a1d736974652f6170695f746d70636861745f64656c6574652e70" .
            "726f746f120473697465222b0a17417069546d706368617444656c657465" .
            "5265717565737412100a08746f557365724964180120012809221a0a1841" .
            "7069546d706368617444656c657465526573706f6e736542580a13636f6d" .
            "2e7a616c792e70726f746f2e736974655a2f6769746875622e636f6d2f64" .
            "75636b636861742f6475636b636861742d676174657761792f70726f746f" .
            "2f73697465ca020f5a616c795c50726f746f5c53697465620670726f746f" .
            "33"
        ));

        static::$is_initialized = true;
    }
}

