<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_user_report.proto

namespace GPBMetadata\Site;

class ApiUserReport
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae7010a1a736974652f6170695f757365725f7265706f72742e70726f74" .
            "6f12047369746522480a14417069557365725265706f7274526571756573" .
            "74120e0a0675736572496418012001280912120a0a7265706f7274547970" .
            "65180220012805120c0a046e6f746518032001280922170a154170695573" .
            "65725265706f7274526573706f6e736542580a13636f6d2e7a616c792e70" .
            "726f746f2e736974655a2f6769746875622e636f6d2f6475636b63686174" .
            "2f6475636b636861742d676174657761792f70726f746f2f73697465ca02" .
            "0f5a616c795c50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

