<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_user_profile.proto

namespace GPBMetadata\Site;

class ApiUserProfile
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0adf010a1b736974652f6170695f757365725f70726f66696c652e70726f" .
            "746f12047369746522170a154170695573657250726f66696c6552657175" .
            "657374223f0a164170695573657250726f66696c65526573706f6e736512" .
            "250a0770726f66696c6518012001280b32142e636f72652e416c6c557365" .
            "7250726f66696c6542580a13636f6d2e7a616c792e70726f746f2e736974" .
            "655a2f6769746875622e636f6d2f6475636b636861742f6475636b636861" .
            "742d676174657761792f70726f746f2f73697465ca020f5a616c795c5072" .
            "6f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

