<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/im_cts.updatePointer.proto

namespace GPBMetadata\Site;

class ImCtsUpdatePointer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abb020a1f736974652f696d5f6374732e757064617465506f696e746572" .
            "2e70726f746f12047369746522af010a19496d437473557064617465506f" .
            "696e7465725265717565737412110a097532506f696e7465721801200128" .
            "0312490a0d67726f757073506f696e74657218022003280b32322e736974" .
            "652e496d437473557064617465506f696e746572526571756573742e4772" .
            "6f757073506f696e746572456e7472791a340a1247726f757073506f696e" .
            "746572456e747279120b0a036b6579180120012809120d0a0576616c7565" .
            "1802200128033a02380142580a13636f6d2e7a616c792e70726f746f2e73" .
            "6974655a2f6769746875622e636f6d2f6475636b636861742f6475636b63" .
            "6861742d676174657761792f70726f746f2f73697465ca020f5a616c795c" .
            "50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

