<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/im_cts_ping.proto

namespace GPBMetadata\Site;

class ImCtsPing
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa4010a16736974652f696d5f6374735f70696e672e70726f746f120473" .
            "69746522220a10496d43747350696e6752657175657374120e0a0672616e" .
            "646f6d18012001280942580a13636f6d2e7a616c792e70726f746f2e7369" .
            "74655a2f6769746875622e636f6d2f6475636b636861742f6475636b6368" .
            "61742d676174657761792f70726f746f2f73697465ca020f5a616c795c50" .
            "726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

