<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/im_cts_message.proto

namespace GPBMetadata\Site;

class ImCtsMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Message::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aba010a19736974652f696d5f6374735f6d6573736167652e70726f746f" .
            "12047369746522350a13496d4374734d6573736167655265717565737412" .
            "1e0a076d65737361676518012001280b320d2e636f72652e4d6573736167" .
            "6542580a13636f6d2e7a616c792e70726f746f2e736974655a2f67697468" .
            "75622e636f6d2f6475636b636861742f6475636b636861742d6761746577" .
            "61792f70726f746f2f73697465ca020f5a616c795c50726f746f5c536974" .
            "65620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

