<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/im_cts_auth.proto

namespace GPBMetadata\Site;

class ImCtsAuth
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa9010a16736974652f696d5f6374735f617574682e70726f746f120473" .
            "69746522120a10496d437473417574685265717565737422130a11496d43" .
            "747341757468526573706f6e736542580a13636f6d2e7a616c792e70726f" .
            "746f2e736974655a2f6769746875622e636f6d2f6475636b636861742f64" .
            "75636b636861742d676174657761792f70726f746f2f73697465ca020f5a" .
            "616c795c50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

