<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_friend_apply.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ApiFriendApplyResponse</code>
 */
class ApiFriendApplyResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Site\ApiFriendApply::initOnce();
        parent::__construct();
    }

}

