<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_friend_search.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: api.friend.search
 *
 * Generated from protobuf message <code>site.ApiFriendSearchRequest</code>
 */
class ApiFriendSearchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *suport phone\loginName
     *
     * Generated from protobuf field <code>string keywords = 1;</code>
     */
    private $keywords = '';
    /**
     * Generated from protobuf field <code>int32 offset = 2;</code>
     */
    private $offset = 0;
    /**
     * default 1000
     *
     * Generated from protobuf field <code>int32 count = 3;</code>
     */
    private $count = 0;

    public function __construct() {
        \GPBMetadata\Site\ApiFriendSearch::initOnce();
        parent::__construct();
    }

    /**
     *suport phone\loginName
     *
     * Generated from protobuf field <code>string keywords = 1;</code>
     * @return string
     */
    public function getKeywords()
    {
        return $this->keywords;
    }

    /**
     *suport phone\loginName
     *
     * Generated from protobuf field <code>string keywords = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKeywords($var)
    {
        GPBUtil::checkString($var, True);
        $this->keywords = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 offset = 2;</code>
     * @return int
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Generated from protobuf field <code>int32 offset = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt32($var);
        $this->offset = $var;

        return $this;
    }

    /**
     * default 1000
     *
     * Generated from protobuf field <code>int32 count = 3;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * default 1000
     *
     * Generated from protobuf field <code>int32 count = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;

        return $this;
    }

}

