<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_friend_update.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ApiFriendUpdateResponse</code>
 */
class ApiFriendUpdateResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.core.FriendUserProfile profile = 1;</code>
     */
    private $profile = null;

    public function __construct() {
        \GPBMetadata\Site\ApiFriendUpdate::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.core.FriendUserProfile profile = 1;</code>
     * @return \Zaly\Proto\Core\FriendUserProfile
     */
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     * Generated from protobuf field <code>.core.FriendUserProfile profile = 1;</code>
     * @param \Zaly\Proto\Core\FriendUserProfile $var
     * @return $this
     */
    public function setProfile($var)
    {
        GPBUtil::checkMessage($var, \Zaly\Proto\Core\FriendUserProfile::class);
        $this->profile = $var;

        return $this;
    }

}

