<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_file_download.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: api.file.download
 * error:
 *.   error.file.none          there's no file
 *.   error.file.permission.   the file is not related to the session user.
 *
 * Generated from protobuf message <code>site.ApiFileDownloadRequest</code>
 */
class ApiFileDownloadRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string fileId = 1;</code>
     */
    private $fileId = '';
    /**
     * Generated from protobuf field <code>bool returnBase64 = 2;</code>
     */
    private $returnBase64 = false;
    /**
     * Generated from protobuf field <code>string messageId = 3;</code>
     */
    private $messageId = '';
    /**
     * Generated from protobuf field <code>bool isGroupMessage = 4;</code>
     */
    private $isGroupMessage = false;

    public function __construct() {
        \GPBMetadata\Site\ApiFileDownload::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string fileId = 1;</code>
     * @return string
     */
    public function getFileId()
    {
        return $this->fileId;
    }

    /**
     * Generated from protobuf field <code>string fileId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFileId($var)
    {
        GPBUtil::checkString($var, True);
        $this->fileId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool returnBase64 = 2;</code>
     * @return bool
     */
    public function getReturnBase64()
    {
        return $this->returnBase64;
    }

    /**
     * Generated from protobuf field <code>bool returnBase64 = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setReturnBase64($var)
    {
        GPBUtil::checkBool($var);
        $this->returnBase64 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string messageId = 3;</code>
     * @return string
     */
    public function getMessageId()
    {
        return $this->messageId;
    }

    /**
     * Generated from protobuf field <code>string messageId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageId($var)
    {
        GPBUtil::checkString($var, True);
        $this->messageId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isGroupMessage = 4;</code>
     * @return bool
     */
    public function getIsGroupMessage()
    {
        return $this->isGroupMessage;
    }

    /**
     * Generated from protobuf field <code>bool isGroupMessage = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsGroupMessage($var)
    {
        GPBUtil::checkBool($var);
        $this->isGroupMessage = $var;

        return $this;
    }

}

