<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_friend_update.proto

namespace Zaly\Proto\Site;

/**
 * Protobuf enum <code>Site\ApiFriendUpdateType</code>
 */
class ApiFriendUpdateType
{
    /**
     * Generated from protobuf enum <code>ApiFriendUpdateInvalid = 0;</code>
     */
    const ApiFriendUpdateInvalid = 0;
    /**
     * Generated from protobuf enum <code>ApiFriendUpdateRemark = 1;</code>
     */
    const ApiFriendUpdateRemark = 1;
    /**
     * Generated from protobuf enum <code>ApiFriendUpdateIsMute = 2;</code>
     */
    const ApiFriendUpdateIsMute = 2;
}

