<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_friend_accept.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: api.friend.accept
 *
 * Generated from protobuf message <code>site.ApiFriendAcceptRequest</code>
 */
class ApiFriendAcceptRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *user who apply me as friend
     *
     * Generated from protobuf field <code>string applyUserId = 1;</code>
     */
    private $applyUserId = '';
    /**
     *true：accept false：refuse
     *
     * Generated from protobuf field <code>bool agree = 2;</code>
     */
    private $agree = false;

    public function __construct() {
        \GPBMetadata\Site\ApiFriendAccept::initOnce();
        parent::__construct();
    }

    /**
     *user who apply me as friend
     *
     * Generated from protobuf field <code>string applyUserId = 1;</code>
     * @return string
     */
    public function getApplyUserId()
    {
        return $this->applyUserId;
    }

    /**
     *user who apply me as friend
     *
     * Generated from protobuf field <code>string applyUserId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setApplyUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->applyUserId = $var;

        return $this;
    }

    /**
     *true：accept false：refuse
     *
     * Generated from protobuf field <code>bool agree = 2;</code>
     * @return bool
     */
    public function getAgree()
    {
        return $this->agree;
    }

    /**
     *true：accept false：refuse
     *
     * Generated from protobuf field <code>bool agree = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setAgree($var)
    {
        GPBUtil::checkBool($var);
        $this->agree = $var;

        return $this;
    }

}

