<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_file_upload.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ApiFileUploadResponse</code>
 */
class ApiFileUploadResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string fileId = 1;</code>
     */
    private $fileId = '';

    public function __construct() {
        \GPBMetadata\Site\ApiFileUpload::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string fileId = 1;</code>
     * @return string
     */
    public function getFileId()
    {
        return $this->fileId;
    }

    /**
     * Generated from protobuf field <code>string fileId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFileId($var)
    {
        GPBUtil::checkString($var, True);
        $this->fileId = $var;

        return $this;
    }

}

