<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_group_members.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ApiGroupMembersResponse</code>
 */
class ApiGroupMembersResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .site.ApiGroupMembersUserProfile list = 1;</code>
     */
    private $list;
    /**
     * Generated from protobuf field <code>int32 totalCount = 2;</code>
     */
    private $totalCount = 0;

    public function __construct() {
        \GPBMetadata\Site\ApiGroupMembers::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .site.ApiGroupMembersUserProfile list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getList()
    {
        return $this->list;
    }

    /**
     * Generated from protobuf field <code>repeated .site.ApiGroupMembersUserProfile list = 1;</code>
     * @param \Zaly\Proto\Site\ApiGroupMembersUserProfile[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zaly\Proto\Site\ApiGroupMembersUserProfile::class);
        $this->list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 totalCount = 2;</code>
     * @return int
     */
    public function getTotalCount()
    {
        return $this->totalCount;
    }

    /**
     * Generated from protobuf field <code>int32 totalCount = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->totalCount = $var;

        return $this;
    }

}

