<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_gw_onDisconnect.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ApiGwOnDisconnectResponse</code>
 */
class ApiGwOnDisconnectResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Site\ApiGwOnDisconnect::initOnce();
        parent::__construct();
    }

}

