<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_gw_onDisconnect.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * No parameters are required.
 *
 * Generated from protobuf message <code>site.ApiGwOnDisconnectRequest</code>
 */
class ApiGwOnDisconnectRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string socketId = 1;</code>
     */
    private $socketId = '';

    public function __construct() {
        \GPBMetadata\Site\ApiGwOnDisconnect::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string socketId = 1;</code>
     * @return string
     */
    public function getSocketId()
    {
        return $this->socketId;
    }

    /**
     * Generated from protobuf field <code>string socketId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSocketId($var)
    {
        GPBUtil::checkString($var, True);
        $this->socketId = $var;

        return $this;
    }

}

