<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_group_invite.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ApiGroupInviteResponse</code>
 */
class ApiGroupInviteResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Site\ApiGroupInvite::initOnce();
        parent::__construct();
    }

}

