<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_group_update.proto

namespace Zaly\Proto\Site;

/**
 * Protobuf enum <code>Site\ApiGroupUpdateType</code>
 */
class ApiGroupUpdateType
{
    /**
     * Generated from protobuf enum <code>ApiGroupUpdateInvalid = 0;</code>
     */
    const ApiGroupUpdateInvalid = 0;
    /**
     * Generated from protobuf enum <code>ApiGroupUpdateName = 1;</code>
     */
    const ApiGroupUpdateName = 1;
    /**
     * Generated from protobuf enum <code>ApiGroupUpdatePermissionJoin = 2;</code>
     */
    const ApiGroupUpdatePermissionJoin = 2;
    /**
     * Generated from protobuf enum <code>ApiGroupUpdateCanGuestReadMessage = 3;</code>
     */
    const ApiGroupUpdateCanGuestReadMessage = 3;
    /**
     * Generated from protobuf enum <code>ApiGroupUpdateDescription = 4;</code>
     */
    const ApiGroupUpdateDescription = 4;
    /**
     * Generated from protobuf enum <code>ApiGroupUpdateAdmin = 5;</code>
     */
    const ApiGroupUpdateAdmin = 5;
    /**
     * Generated from protobuf enum <code>ApiGroupUpdateSpeaker = 6;</code>
     */
    const ApiGroupUpdateSpeaker = 6;
    /**
     * Generated from protobuf enum <code>ApiGroupUpdateIsMute = 7;</code>
     */
    const ApiGroupUpdateIsMute = 7;
}

