<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_gw_config.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ApiGwConfigResponse</code>
 */
class ApiGwConfigResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string socketIdSalt = 1;</code>
     */
    private $socketIdSalt = '';

    public function __construct() {
        \GPBMetadata\Site\ApiGwConfig::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string socketIdSalt = 1;</code>
     * @return string
     */
    public function getSocketIdSalt()
    {
        return $this->socketIdSalt;
    }

    /**
     * Generated from protobuf field <code>string socketIdSalt = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSocketIdSalt($var)
    {
        GPBUtil::checkString($var, True);
        $this->socketIdSalt = $var;

        return $this;
    }

}

