<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_group_setSpeaker.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ApiGroupSetSpeakerResponse</code>
 */
class ApiGroupSetSpeakerResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string speakerUserIds = 1;</code>
     */
    private $speakerUserIds;

    public function __construct() {
        \GPBMetadata\Site\ApiGroupSetSpeaker::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated string speakerUserIds = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpeakerUserIds()
    {
        return $this->speakerUserIds;
    }

    /**
     * Generated from protobuf field <code>repeated string speakerUserIds = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpeakerUserIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->speakerUserIds = $arr;

        return $this;
    }

}

