<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_group_create.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: api.group.create
 *
 * Generated from protobuf message <code>site.ApiGroupCreateRequest</code>
 */
class ApiGroupCreateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string groupName = 1;</code>
     */
    private $groupName = '';

    public function __construct() {
        \GPBMetadata\Site\ApiGroupCreate::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string groupName = 1;</code>
     * @return string
     */
    public function getGroupName()
    {
        return $this->groupName;
    }

    /**
     * Generated from protobuf field <code>string groupName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupName($var)
    {
        GPBUtil::checkString($var, True);
        $this->groupName = $var;

        return $this;
    }

}

