<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_group_invitableFriends.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ApiGroupInvitableFriendsResponse</code>
 */
class ApiGroupInvitableFriendsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .core.PublicUserProfile list = 1;</code>
     */
    private $list;
    /**
     * Generated from protobuf field <code>map<string, bool> listIsMute = 2;</code>
     */
    private $listIsMute;
    /**
     * Generated from protobuf field <code>int32 totalCount = 3;</code>
     */
    private $totalCount = 0;

    public function __construct() {
        \GPBMetadata\Site\ApiGroupInvitableFriends::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .core.PublicUserProfile list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getList()
    {
        return $this->list;
    }

    /**
     * Generated from protobuf field <code>repeated .core.PublicUserProfile list = 1;</code>
     * @param \Zaly\Proto\Core\PublicUserProfile[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zaly\Proto\Core\PublicUserProfile::class);
        $this->list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, bool> listIsMute = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getListIsMute()
    {
        return $this->listIsMute;
    }

    /**
     * Generated from protobuf field <code>map<string, bool> listIsMute = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setListIsMute($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::BOOL);
        $this->listIsMute = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 totalCount = 3;</code>
     * @return int
     */
    public function getTotalCount()
    {
        return $this->totalCount;
    }

    /**
     * Generated from protobuf field <code>int32 totalCount = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->totalCount = $var;

        return $this;
    }

}

