<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_group_delete.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ApiGroupDeleteResponse</code>
 */
class ApiGroupDeleteResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Site\ApiGroupDelete::initOnce();
        parent::__construct();
    }

}

