<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_group_setSpeaker.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ApiGroupSetSpeakerRequest</code>
 */
class ApiGroupSetSpeakerRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string groupId = 1;</code>
     */
    private $groupId = '';
    /**
     * Generated from protobuf field <code>.site.SetSpeakerType setType = 2;</code>
     */
    private $setType = 0;
    /**
     * Generated from protobuf field <code>repeated string speakerUserIds = 3;</code>
     */
    private $speakerUserIds;

    public function __construct() {
        \GPBMetadata\Site\ApiGroupSetSpeaker::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string groupId = 1;</code>
     * @return string
     */
    public function getGroupId()
    {
        return $this->groupId;
    }

    /**
     * Generated from protobuf field <code>string groupId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->groupId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.site.SetSpeakerType setType = 2;</code>
     * @return int
     */
    public function getSetType()
    {
        return $this->setType;
    }

    /**
     * Generated from protobuf field <code>.site.SetSpeakerType setType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSetType($var)
    {
        GPBUtil::checkEnum($var, \Zaly\Proto\Site\SetSpeakerType::class);
        $this->setType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string speakerUserIds = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpeakerUserIds()
    {
        return $this->speakerUserIds;
    }

    /**
     * Generated from protobuf field <code>repeated string speakerUserIds = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpeakerUserIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->speakerUserIds = $arr;

        return $this;
    }

}

