<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_message_checkStatus.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ApiMessageCheckStatusResponse</code>
 */
class ApiMessageCheckStatusResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .core.StatusMessage statusMessages = 1;</code>
     */
    private $statusMessages;

    public function __construct() {
        \GPBMetadata\Site\ApiMessageCheckStatus::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .core.StatusMessage statusMessages = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStatusMessages()
    {
        return $this->statusMessages;
    }

    /**
     * Generated from protobuf field <code>repeated .core.StatusMessage statusMessages = 1;</code>
     * @param \Zaly\Proto\Core\StatusMessage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStatusMessages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zaly\Proto\Core\StatusMessage::class);
        $this->statusMessages = $arr;

        return $this;
    }

}

