<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_message_checkStatus.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: api.message.checkStatus
 *
 * Generated from protobuf message <code>site.ApiMessageCheckStatusRequest</code>
 */
class ApiMessageCheckStatusRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string msgIds = 1;</code>
     */
    private $msgIds;
    /**
     * Generated from protobuf field <code>.core.MessageRoomType roomType = 2;</code>
     */
    private $roomType = 0;

    public function __construct() {
        \GPBMetadata\Site\ApiMessageCheckStatus::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated string msgIds = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMsgIds()
    {
        return $this->msgIds;
    }

    /**
     * Generated from protobuf field <code>repeated string msgIds = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMsgIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->msgIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.core.MessageRoomType roomType = 2;</code>
     * @return int
     */
    public function getRoomType()
    {
        return $this->roomType;
    }

    /**
     * Generated from protobuf field <code>.core.MessageRoomType roomType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRoomType($var)
    {
        GPBUtil::checkEnum($var, \Zaly\Proto\Core\MessageRoomType::class);
        $this->roomType = $var;

        return $this;
    }

}

