<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_plugin_proxy.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ApiPluginProxyResponse</code>
 */
class ApiPluginProxyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes body = 1;</code>
     */
    private $body = '';
    /**
     * Generated from protobuf field <code>int32 httpCode = 2;</code>
     */
    private $httpCode = 0;
    /**
     * Generated from protobuf field <code>map<string, string> headers = 3;</code>
     */
    private $headers;

    public function __construct() {
        \GPBMetadata\Site\ApiPluginProxy::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bytes body = 1;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>bytes body = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 httpCode = 2;</code>
     * @return int
     */
    public function getHttpCode()
    {
        return $this->httpCode;
    }

    /**
     * Generated from protobuf field <code>int32 httpCode = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setHttpCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->httpCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> headers = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    /**
     * Generated from protobuf field <code>map<string, string> headers = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setHeaders($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->headers = $arr;

        return $this;
    }

}

