<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_passport_password_findPassword.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: api.passport.password.findPassword
 *
 * Generated from protobuf message <code>site.ApiPassportPasswordFindPasswordRequest</code>
 */
class ApiPassportPasswordFindPasswordRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string loginName = 1;</code>
     */
    private $loginName = '';

    public function __construct() {
        \GPBMetadata\Site\ApiPassportPasswordFindPassword::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string loginName = 1;</code>
     * @return string
     */
    public function getLoginName()
    {
        return $this->loginName;
    }

    /**
     * Generated from protobuf field <code>string loginName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLoginName($var)
    {
        GPBUtil::checkString($var, True);
        $this->loginName = $var;

        return $this;
    }

}

