<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_passport_ldap_login.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: api.passport.ldap.login
 * error:
 *
 * Generated from protobuf message <code>site.ApiPassportLdapLoginRequest</code>
 */
class ApiPassportLdapLoginRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string account = 1;</code>
     */
    private $account = '';
    /**
     * Generated from protobuf field <code>string password = 2;</code>
     */
    private $password = '';

    public function __construct() {
        \GPBMetadata\Site\ApiPassportLdapLogin::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string account = 1;</code>
     * @return string
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     * Generated from protobuf field <code>string account = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkString($var, True);
        $this->account = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

}

