<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_sync_check.proto

namespace Zaly\Proto\Site;

/**
 * Protobuf enum <code>Site\ApiSyncType</code>
 */
class ApiSyncType
{
    /**
     * Generated from protobuf enum <code>ApiSyncInvalid = 0;</code>
     */
    const ApiSyncInvalid = 0;
    /**
     * Generated from protobuf enum <code>ApiSyncFriendList = 1;</code>
     */
    const ApiSyncFriendList = 1;
}

