<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_sync_check.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: api.sync.check
 *
 * Generated from protobuf message <code>site.ApiSyncCheckRequest</code>
 */
class ApiSyncCheckRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.site.ApiSyncType type = 1;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>int32 localVersion = 2;</code>
     */
    private $localVersion = 0;

    public function __construct() {
        \GPBMetadata\Site\ApiSyncCheck::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.site.ApiSyncType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.site.ApiSyncType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Zaly\Proto\Site\ApiSyncType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 localVersion = 2;</code>
     * @return int
     */
    public function getLocalVersion()
    {
        return $this->localVersion;
    }

    /**
     * Generated from protobuf field <code>int32 localVersion = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLocalVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->localVersion = $var;

        return $this;
    }

}

