<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_site_logout.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ApiSiteLogoutResponse</code>
 */
class ApiSiteLogoutResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Site\ApiSiteLogout::initOnce();
        parent::__construct();
    }

}

