<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_tmpchat_delete.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: api.tmpchat.delete
 *
 * Generated from protobuf message <code>site.ApiTmpchatDeleteRequest</code>
 */
class ApiTmpchatDeleteRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string toUserId = 1;</code>
     */
    private $toUserId = '';

    public function __construct() {
        \GPBMetadata\Site\ApiTmpchatDelete::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string toUserId = 1;</code>
     * @return string
     */
    public function getToUserId()
    {
        return $this->toUserId;
    }

    /**
     * Generated from protobuf field <code>string toUserId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->toUserId = $var;

        return $this;
    }

}

