<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_tmpchat_group.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ApiTmpchatGroupResponse</code>
 */
class ApiTmpchatGroupResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Site\ApiTmpchatGroup::initOnce();
        parent::__construct();
    }

}

