<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_user_profile.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: api.user.profile
 *
 * Generated from protobuf message <code>site.ApiUserProfileRequest</code>
 */
class ApiUserProfileRequest extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Site\ApiUserProfile::initOnce();
        parent::__construct();
    }

}

