<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_user_update.proto

namespace Zaly\Proto\Site;

/**
 * Protobuf enum <code>Site\ApiUserUpdateType</code>
 */
class ApiUserUpdateType
{
    /**
     * Generated from protobuf enum <code>ApiUserUpdateInvalid = 0;</code>
     */
    const ApiUserUpdateInvalid = 0;
    /**
     * Generated from protobuf enum <code>ApiUserUpdateAvatar = 1;</code>
     */
    const ApiUserUpdateAvatar = 1;
    /**
     * Generated from protobuf enum <code>ApiUserUpdateNickname = 2;</code>
     */
    const ApiUserUpdateNickname = 2;
    /**
     * Generated from protobuf enum <code>ApiUserUpdateCustom = 3;</code>
     */
    const ApiUserUpdateCustom = 3;
}

