<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_user_report.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ApiUserReportResponse</code>
 */
class ApiUserReportResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Site\ApiUserReport::initOnce();
        parent::__construct();
    }

}

