<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_user_update.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: api.user.update
 *
 * Generated from protobuf message <code>site.ApiUserUpdateRequest</code>
 */
class ApiUserUpdateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .site.ApiUserUpdateValue values = 2;</code>
     */
    private $values;

    public function __construct() {
        \GPBMetadata\Site\ApiUserUpdate::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .site.ApiUserUpdateValue values = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Generated from protobuf field <code>repeated .site.ApiUserUpdateValue values = 2;</code>
     * @param \Zaly\Proto\Site\ApiUserUpdateValue[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zaly\Proto\Site\ApiUserUpdateValue::class);
        $this->values = $arr;

        return $this;
    }

}

