<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/im_cts.updatePointer.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: im.cts.updatePointer
 *
 * Generated from protobuf message <code>site.ImCtsUpdatePointerRequest</code>
 */
class ImCtsUpdatePointerRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 u2Pointer = 1;</code>
     */
    private $u2Pointer = 0;
    /**
     * Generated from protobuf field <code>map<string, int64> groupsPointer = 2;</code>
     */
    private $groupsPointer;

    public function __construct() {
        \GPBMetadata\Site\ImCtsUpdatePointer::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 u2Pointer = 1;</code>
     * @return int|string
     */
    public function getU2Pointer()
    {
        return $this->u2Pointer;
    }

    /**
     * Generated from protobuf field <code>int64 u2Pointer = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setU2Pointer($var)
    {
        GPBUtil::checkInt64($var);
        $this->u2Pointer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, int64> groupsPointer = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getGroupsPointer()
    {
        return $this->groupsPointer;
    }

    /**
     * Generated from protobuf field <code>map<string, int64> groupsPointer = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setGroupsPointer($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::INT64);
        $this->groupsPointer = $arr;

        return $this;
    }

}

