<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/im_cts_message.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **：
 * 	action: im.cts.message
 *
 * Generated from protobuf message <code>site.ImCtsMessageRequest</code>
 */
class ImCtsMessageRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.core.Message message = 1;</code>
     */
    private $message = null;

    public function __construct() {
        \GPBMetadata\Site\ImCtsMessage::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.core.Message message = 1;</code>
     * @return \Zaly\Proto\Core\Message
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>.core.Message message = 1;</code>
     * @param \Zaly\Proto\Core\Message $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkMessage($var, \Zaly\Proto\Core\Message::class);
        $this->message = $var;

        return $this;
    }

}

