<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/im_cts_auth.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.ImCtsAuthResponse</code>
 */
class ImCtsAuthResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Site\ImCtsAuth::initOnce();
        parent::__construct();
    }

}

