<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/im_cts_sync.proto

namespace Zaly\Proto\Site;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: im.cts.sync
 *
 * Generated from protobuf message <code>site.ImCtsSyncRequest</code>
 */
class ImCtsSyncRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 u2Count = 1;</code>
     */
    private $u2Count = 0;
    /**
     * Generated from protobuf field <code>int32 groupCount = 2;</code>
     */
    private $groupCount = 0;
    /**
     * if true: update the user's pointer to the value in MessageSyncReq
     * for http-only server.
     *
     * Generated from protobuf field <code>bool updatePointer = 3;</code>
     */
    private $updatePointer = false;

    public function __construct() {
        \GPBMetadata\Site\ImCtsSync::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 u2Count = 1;</code>
     * @return int
     */
    public function getU2Count()
    {
        return $this->u2Count;
    }

    /**
     * Generated from protobuf field <code>int32 u2Count = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setU2Count($var)
    {
        GPBUtil::checkInt32($var);
        $this->u2Count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 groupCount = 2;</code>
     * @return int
     */
    public function getGroupCount()
    {
        return $this->groupCount;
    }

    /**
     * Generated from protobuf field <code>int32 groupCount = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setGroupCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->groupCount = $var;

        return $this;
    }

    /**
     * if true: update the user's pointer to the value in MessageSyncReq
     * for http-only server.
     *
     * Generated from protobuf field <code>bool updatePointer = 3;</code>
     * @return bool
     */
    public function getUpdatePointer()
    {
        return $this->updatePointer;
    }

    /**
     * if true: update the user's pointer to the value in MessageSyncReq
     * for http-only server.
     *
     * Generated from protobuf field <code>bool updatePointer = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setUpdatePointer($var)
    {
        GPBUtil::checkBool($var);
        $this->updatePointer = $var;

        return $this;
    }

}

