<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_group_setSpeaker.proto

namespace Zaly\Proto\Site;

/**
 * Protobuf enum <code>Site\SetSpeakerType</code>
 */
class SetSpeakerType
{
    /**
     *add new speakers
     *
     * Generated from protobuf enum <code>AddSpeaker = 0;</code>
     */
    const AddSpeaker = 0;
    /**
     *remove old speakers
     *
     * Generated from protobuf enum <code>RemoveSpeaker = 1;</code>
     */
    const RemoveSpeaker = 1;
    /**
     *close speaker function
     *
     * Generated from protobuf enum <code>CloseSpeaker = 2;</code>
     */
    const CloseSpeaker = 2;
}

