<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/group.proto

namespace Zaly\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * TODO:
 * remove this message
 *
 * Generated from protobuf message <code>core.AllGroupProfile</code>
 */
class AllGroupProfile extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.core.PublicGroupProfile profile = 1;</code>
     */
    private $profile = null;
    /**
     * Generated from protobuf field <code>.core.PublicUserProfile owner = 2;</code>
     */
    private $owner = null;
    /**
     * Generated from protobuf field <code>repeated .core.PublicUserProfile admins = 3;</code>
     */
    private $admins;
    /**
     * Generated from protobuf field <code>repeated .core.PublicUserProfile speakers = 4;</code>
     */
    private $speakers;

    public function __construct() {
        \GPBMetadata\Core\Group::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.core.PublicGroupProfile profile = 1;</code>
     * @return \Zaly\Proto\Core\PublicGroupProfile
     */
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     * Generated from protobuf field <code>.core.PublicGroupProfile profile = 1;</code>
     * @param \Zaly\Proto\Core\PublicGroupProfile $var
     * @return $this
     */
    public function setProfile($var)
    {
        GPBUtil::checkMessage($var, \Zaly\Proto\Core\PublicGroupProfile::class);
        $this->profile = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.core.PublicUserProfile owner = 2;</code>
     * @return \Zaly\Proto\Core\PublicUserProfile
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * Generated from protobuf field <code>.core.PublicUserProfile owner = 2;</code>
     * @param \Zaly\Proto\Core\PublicUserProfile $var
     * @return $this
     */
    public function setOwner($var)
    {
        GPBUtil::checkMessage($var, \Zaly\Proto\Core\PublicUserProfile::class);
        $this->owner = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .core.PublicUserProfile admins = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAdmins()
    {
        return $this->admins;
    }

    /**
     * Generated from protobuf field <code>repeated .core.PublicUserProfile admins = 3;</code>
     * @param \Zaly\Proto\Core\PublicUserProfile[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAdmins($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zaly\Proto\Core\PublicUserProfile::class);
        $this->admins = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .core.PublicUserProfile speakers = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpeakers()
    {
        return $this->speakers;
    }

    /**
     * Generated from protobuf field <code>repeated .core.PublicUserProfile speakers = 4;</code>
     * @param \Zaly\Proto\Core\PublicUserProfile[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpeakers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zaly\Proto\Core\PublicUserProfile::class);
        $this->speakers = $arr;

        return $this;
    }

}

