<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/site.proto

namespace Zaly\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * all the configurations, private!
 *
 * Generated from protobuf message <code>core.AllSiteConfig</code>
 */
class AllSiteConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.core.PublicSiteConfig public = 1;</code>
     */
    private $public = null;
    /**
     * Generated from protobuf field <code>.core.HooksType HooksType = 2;</code>
     */
    private $HooksType = 0;
    /**
     * Generated from protobuf field <code>string hooksRedisServer = 3;</code>
     */
    private $hooksRedisServer = '';
    /**
     * Generated from protobuf field <code>.core.PushType PushType = 4;</code>
     */
    private $PushType = 0;
    /**
     * Generated from protobuf field <code>string siteIdPrikBase64 = 5;</code>
     */
    private $siteIdPrikBase64 = '';
    /**
     * Generated from protobuf field <code>string maxGroupMembers = 6;</code>
     */
    private $maxGroupMembers = '';
    /**
     * Generated from protobuf field <code>int32 groupInvitationUrlExpiration = 7;</code>
     */
    private $groupInvitationUrlExpiration = 0;
    /**
     * Generated from protobuf field <code>int32 maxClientsNum = 8;</code>
     */
    private $maxClientsNum = 0;

    public function __construct() {
        \GPBMetadata\Core\Site::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.core.PublicSiteConfig public = 1;</code>
     * @return \Zaly\Proto\Core\PublicSiteConfig
     */
    public function getPublic()
    {
        return $this->public;
    }

    /**
     * Generated from protobuf field <code>.core.PublicSiteConfig public = 1;</code>
     * @param \Zaly\Proto\Core\PublicSiteConfig $var
     * @return $this
     */
    public function setPublic($var)
    {
        GPBUtil::checkMessage($var, \Zaly\Proto\Core\PublicSiteConfig::class);
        $this->public = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.core.HooksType HooksType = 2;</code>
     * @return int
     */
    public function getHooksType()
    {
        return $this->HooksType;
    }

    /**
     * Generated from protobuf field <code>.core.HooksType HooksType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setHooksType($var)
    {
        GPBUtil::checkEnum($var, \Zaly\Proto\Core\HooksType::class);
        $this->HooksType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string hooksRedisServer = 3;</code>
     * @return string
     */
    public function getHooksRedisServer()
    {
        return $this->hooksRedisServer;
    }

    /**
     * Generated from protobuf field <code>string hooksRedisServer = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHooksRedisServer($var)
    {
        GPBUtil::checkString($var, True);
        $this->hooksRedisServer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.core.PushType PushType = 4;</code>
     * @return int
     */
    public function getPushType()
    {
        return $this->PushType;
    }

    /**
     * Generated from protobuf field <code>.core.PushType PushType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPushType($var)
    {
        GPBUtil::checkEnum($var, \Zaly\Proto\Core\PushType::class);
        $this->PushType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string siteIdPrikBase64 = 5;</code>
     * @return string
     */
    public function getSiteIdPrikBase64()
    {
        return $this->siteIdPrikBase64;
    }

    /**
     * Generated from protobuf field <code>string siteIdPrikBase64 = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteIdPrikBase64($var)
    {
        GPBUtil::checkString($var, True);
        $this->siteIdPrikBase64 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string maxGroupMembers = 6;</code>
     * @return string
     */
    public function getMaxGroupMembers()
    {
        return $this->maxGroupMembers;
    }

    /**
     * Generated from protobuf field <code>string maxGroupMembers = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMaxGroupMembers($var)
    {
        GPBUtil::checkString($var, True);
        $this->maxGroupMembers = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 groupInvitationUrlExpiration = 7;</code>
     * @return int
     */
    public function getGroupInvitationUrlExpiration()
    {
        return $this->groupInvitationUrlExpiration;
    }

    /**
     * Generated from protobuf field <code>int32 groupInvitationUrlExpiration = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setGroupInvitationUrlExpiration($var)
    {
        GPBUtil::checkInt32($var);
        $this->groupInvitationUrlExpiration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 maxClientsNum = 8;</code>
     * @return int
     */
    public function getMaxClientsNum()
    {
        return $this->maxClientsNum;
    }

    /**
     * Generated from protobuf field <code>int32 maxClientsNum = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxClientsNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->maxClientsNum = $var;

        return $this;
    }

}

