<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/site.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\BuiltinPluginId</code>
 */
class BuiltinPluginId
{
    /**
     * Generated from protobuf enum <code>PluginInvalid = 0;</code>
     */
    const PluginInvalid = 0;
    /**
     * Generated from protobuf enum <code>PluginAdmin = 1;</code>
     */
    const PluginAdmin = 1;
    /**
     * Generated from protobuf enum <code>PluginPlaza = 2;</code>
     */
    const PluginPlaza = 2;
    /**
     * Generated from protobuf enum <code>PluginLoginByPlatform = 3;</code>
     */
    const PluginLoginByPlatform = 3;
    /**
     * Generated from protobuf enum <code>PluginLoginByPassword = 4;</code>
     */
    const PluginLoginByPassword = 4;
    /**
     * Generated from protobuf enum <code>PluginLoginByUsernameOnly = 5;</code>
     */
    const PluginLoginByUsernameOnly = 5;
    /**
     * Generated from protobuf enum <code>PluginLoginByCert = 6;</code>
     */
    const PluginLoginByCert = 6;
    /**
     * Generated from protobuf enum <code>PluginLoginByLdap = 7;</code>
     */
    const PluginLoginByLdap = 7;
}

