<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/custom.proto

namespace Zaly\Proto\Core;

/**
 *
 * Protobuf enum <code>Core\CustomDataType</code>
 */
class CustomDataType
{
    /**
     * Generated from protobuf enum <code>DataTypeInvalid = 0;</code>
     */
    const DataTypeInvalid = 0;
    /**
     * Generated from protobuf enum <code>DataTypeText = 1;</code>
     */
    const DataTypeText = 1;
    /**
     * Generated from protobuf enum <code>DataTypeInt = 2;</code>
     */
    const DataTypeInt = 2;
}

