<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/custom.proto

namespace Zaly\Proto\Core;

/**
 *
 * Protobuf enum <code>Core\CustomType</code>
 */
class CustomType
{
    /**
     * Generated from protobuf enum <code>CustomTypeInvalid = 0;</code>
     */
    const CustomTypeInvalid = 0;
    /**
     * Generated from protobuf enum <code>CustomTypeLogin = 1;</code>
     */
    const CustomTypeLogin = 1;
    /**
     * Generated from protobuf enum <code>CustomTypeUser = 2;</code>
     */
    const CustomTypeUser = 2;
}

