<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/net.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\DataWriteType</code>
 */
class DataWriteType
{
    /**
     * db = requestValue
     *
     * Generated from protobuf enum <code>WriteUpdate = 0;</code>
     */
    const WriteUpdate = 0;
    /**
     * db = db + requestValue
     *
     * Generated from protobuf enum <code>WriteAdd = 1;</code>
     */
    const WriteAdd = 1;
    /**
     * db = db - requestValue
     *
     * Generated from protobuf enum <code>WriteDel = 2;</code>
     */
    const WriteDel = 2;
}

