<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/user.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\FriendRelationType</code>
 */
class FriendRelationType
{
    /**
     * Generated from protobuf enum <code>FriendRelationInvalid = 0;</code>
     */
    const FriendRelationInvalid = 0;
    /**
     * Generated from protobuf enum <code>FriendRelationFollow = 1;</code>
     */
    const FriendRelationFollow = 1;
    /**
     * Generated from protobuf enum <code>FriendRelationFollowForGroup = 2;</code>
     */
    const FriendRelationFollowForGroup = 2;
    /**
     * Generated from protobuf enum <code>FriendRelationFollowForWeb = 3;</code>
     */
    const FriendRelationFollowForWeb = 3;
}

