<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/site.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\FrontPage</code>
 */
class FrontPage
{
    /**
     * Generated from protobuf enum <code>FrontPageDefault = 0;</code>
     */
    const FrontPageDefault = 0;
    /**
     * Generated from protobuf enum <code>FrontPageHome = 1;</code>
     */
    const FrontPageHome = 1;
    /**
     * Generated from protobuf enum <code>FrontPageChats = 2;</code>
     */
    const FrontPageChats = 2;
    /**
     * Generated from protobuf enum <code>FrontPageContacts = 3;</code>
     */
    const FrontPageContacts = 3;
    /**
     * Generated from protobuf enum <code>FrontPageMe = 4;</code>
     */
    const FrontPageMe = 4;
}

