<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/net.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\GatewayType</code>
 */
class GatewayType
{
    /**
     * Generated from protobuf enum <code>GatewayInvalid = 0;</code>
     */
    const GatewayInvalid = 0;
    /**
     * Generated from protobuf enum <code>GatewayWebsocket = 1;</code>
     */
    const GatewayWebsocket = 1;
    /**
     * Generated from protobuf enum <code>GatewayZaly = 2;</code>
     */
    const GatewayZaly = 2;
}

