<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/group.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\GroupDescriptionType</code>
 */
class GroupDescriptionType
{
    /**
     * Generated from protobuf enum <code>GroupDescriptionText = 0;</code>
     */
    const GroupDescriptionText = 0;
    /**
     * Generated from protobuf enum <code>GroupDescriptionMarkdown = 1;</code>
     */
    const GroupDescriptionMarkdown = 1;
}

