<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/group.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\GroupJoinPermissionType</code>
 */
class GroupJoinPermissionType
{
    /**
     * Generated from protobuf enum <code>GroupJoinPermissionPublic = 0;</code>
     */
    const GroupJoinPermissionPublic = 0;
    /**
     * Generated from protobuf enum <code>GroupJoinPermissionMember = 1;</code>
     */
    const GroupJoinPermissionMember = 1;
    /**
     * Generated from protobuf enum <code>GroupJoinPermissionAdmin = 2;</code>
     */
    const GroupJoinPermissionAdmin = 2;
}

