<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/group.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\GroupMemberType</code>
 */
class GroupMemberType
{
    /**
     * Generated from protobuf enum <code>GroupMemberGuest = 0;</code>
     */
    const GroupMemberGuest = 0;
    /**
     * Generated from protobuf enum <code>GroupMemberNormal = 1;</code>
     */
    const GroupMemberNormal = 1;
    /**
     * Generated from protobuf enum <code>GroupMemberAdmin = 2;</code>
     */
    const GroupMemberAdmin = 2;
    /**
     * Generated from protobuf enum <code>GroupMemberOwner = 3;</code>
     */
    const GroupMemberOwner = 3;
}

