<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/group.proto

namespace Zaly\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>core.GroupDescription</code>
 */
class GroupDescription extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.core.GroupDescriptionType type = 1;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>string body = 2;</code>
     */
    private $body = '';

    public function __construct() {
        \GPBMetadata\Core\Group::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.core.GroupDescriptionType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.core.GroupDescriptionType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Zaly\Proto\Core\GroupDescriptionType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string body = 2;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>string body = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->body = $var;

        return $this;
    }

}

