<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/site.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\HooksType</code>
 */
class HooksType
{
    /**
     * Generated from protobuf enum <code>HooksInvalid = 0;</code>
     */
    const HooksInvalid = 0;
    /**
     * Generated from protobuf enum <code>HooksByHttp = 1;</code>
     */
    const HooksByHttp = 1;
    /**
     * Generated from protobuf enum <code>HooksByRedis = 2;</code>
     */
    const HooksByRedis = 2;
}

