<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/net.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\HttpQueryType</code>
 */
class HttpQueryType
{
    /**
     * Generated from protobuf enum <code>HttpQueryInvalid = 0;</code>
     */
    const HttpQueryInvalid = 0;
    /**
     * Generated from protobuf enum <code>HttpQueryGet = 1;</code>
     */
    const HttpQueryGet = 1;
    /**
     * Generated from protobuf enum <code>HttpQueryPost = 2;</code>
     */
    const HttpQueryPost = 2;
}

