<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/custom.proto

namespace Zaly\Proto\Core;

/**
 *
 * Protobuf enum <code>Core\LoginCustomStatus</code>
 */
class LoginCustomStatus
{
    /**
     * Generated from protobuf enum <code>LoginCustomInvalid = 0;</code>
     */
    const LoginCustomInvalid = 0;
    /**
     * Generated from protobuf enum <code>LoginCustomNormal = 1;</code>
     */
    const LoginCustomNormal = 1;
}

