<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/message.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\MessageRoomType</code>
 */
class MessageRoomType
{
    /**
     * Generated from protobuf enum <code>MessageRoomGroup = 0;</code>
     */
    const MessageRoomGroup = 0;
    /**
     * Generated from protobuf enum <code>MessageRoomU2 = 1;</code>
     */
    const MessageRoomU2 = 1;
}

