<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/message.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\MessageStatus</code>
 */
class MessageStatus
{
    /**
     * Generated from protobuf enum <code>MessageStatusUnsent = 0;</code>
     */
    const MessageStatusUnsent = 0;
    /**
     * client only.
     *
     * Generated from protobuf enum <code>MessageStatusSending = 1;</code>
     */
    const MessageStatusSending = 1;
    /**
     * Generated from protobuf enum <code>MessageStatusFailed = 3;</code>
     */
    const MessageStatusFailed = 3;
    /**
     * Generated from protobuf enum <code>MessageStatusServer = 4;</code>
     */
    const MessageStatusServer = 4;
}

