<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/message.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\MessageType</code>
 */
class MessageType
{
    /**
     * Generated from protobuf enum <code>MessageInvalid = 0;</code>
     */
    const MessageInvalid = 0;
    /**
     * Generated from protobuf enum <code>MessageNotice = 1;</code>
     */
    const MessageNotice = 1;
    /**
     * Generated from protobuf enum <code>MessageText = 2;</code>
     */
    const MessageText = 2;
    /**
     * Generated from protobuf enum <code>MessageImage = 3;</code>
     */
    const MessageImage = 3;
    /**
     * Generated from protobuf enum <code>MessageAudio = 4;</code>
     */
    const MessageAudio = 4;
    /**
     * Generated from protobuf enum <code>MessageWeb = 5;</code>
     */
    const MessageWeb = 5;
    /**
     * Generated from protobuf enum <code>MessageWebNotice = 6;</code>
     */
    const MessageWebNotice = 6;
    /**
     * Generated from protobuf enum <code>MessageDocument = 7;</code>
     */
    const MessageDocument = 7;
    /**
     * Generated from protobuf enum <code>MessageVideo = 8;</code>
     */
    const MessageVideo = 8;
    /**
     * Generated from protobuf enum <code>MessageRecall = 9;</code>
     */
    const MessageRecall = 9;
    /**
     * event message start
     *
     * Generated from protobuf enum <code>MessageEventFriendRequest = 20;</code>
     */
    const MessageEventFriendRequest = 20;
    /**
     * NoDB    -> StatusMessage
     *
     * Generated from protobuf enum <code>MessageEventStatus = 21;</code>
     */
    const MessageEventStatus = 21;
    /**
     * NoDB    -> there's no new message in server.
     *
     * Generated from protobuf enum <code>MessageEventSyncEnd = 22;</code>
     */
    const MessageEventSyncEnd = 22;
}

