<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/plugin.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\PluginLoadingType</code>
 */
class PluginLoadingType
{
    /**
     * Generated from protobuf enum <code>PluginLoadingNewPage = 0;</code>
     */
    const PluginLoadingNewPage = 0;
    /**
     * Generated from protobuf enum <code>PluginLoadingFloat = 1;</code>
     */
    const PluginLoadingFloat = 1;
    /**
     * Generated from protobuf enum <code>PluginLoadingMask = 2;</code>
     */
    const PluginLoadingMask = 2;
    /**
     * Generated from protobuf enum <code>PluginLoadingChatbox = 3;</code>
     */
    const PluginLoadingChatbox = 3;
    /**
     * Generated from protobuf enum <code>PluginLoadingFullScreen = 4;</code>
     */
    const PluginLoadingFullScreen = 4;
}

