<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/plugin.proto

namespace Zaly\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>core.PluginProfile</code>
 */
class PluginProfile extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string logo = 3;</code>
     */
    private $logo = '';
    /**
     * Generated from protobuf field <code>int32 order = 4;</code>
     */
    private $order = 0;
    /**
     * Generated from protobuf field <code>string landingPageUrl = 5;</code>
     */
    private $landingPageUrl = '';
    /**
     * Generated from protobuf field <code>bool landingPageWithProxy = 6;</code>
     */
    private $landingPageWithProxy = false;
    /**
     * Generated from protobuf field <code>repeated .core.PluginUsageType usageTypes = 7;</code>
     */
    private $usageTypes;
    /**
     * Generated from protobuf field <code>.core.PluginLoadingType loadingType = 8;</code>
     */
    private $loadingType = 0;
    /**
     * Generated from protobuf field <code>.core.PluginPermissionType permissionType = 9;</code>
     */
    private $permissionType = 0;
    /**
     * Generated from protobuf field <code>string userSessionId = 10;</code>
     */
    private $userSessionId = '';
    /**
     *小程序管理url
     *
     * Generated from protobuf field <code>string adminPageUrl = 11;</code>
     */
    private $adminPageUrl = '';

    public function __construct() {
        \GPBMetadata\Core\Plugin::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string logo = 3;</code>
     * @return string
     */
    public function getLogo()
    {
        return $this->logo;
    }

    /**
     * Generated from protobuf field <code>string logo = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLogo($var)
    {
        GPBUtil::checkString($var, True);
        $this->logo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 order = 4;</code>
     * @return int
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * Generated from protobuf field <code>int32 order = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setOrder($var)
    {
        GPBUtil::checkInt32($var);
        $this->order = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string landingPageUrl = 5;</code>
     * @return string
     */
    public function getLandingPageUrl()
    {
        return $this->landingPageUrl;
    }

    /**
     * Generated from protobuf field <code>string landingPageUrl = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setLandingPageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->landingPageUrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool landingPageWithProxy = 6;</code>
     * @return bool
     */
    public function getLandingPageWithProxy()
    {
        return $this->landingPageWithProxy;
    }

    /**
     * Generated from protobuf field <code>bool landingPageWithProxy = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setLandingPageWithProxy($var)
    {
        GPBUtil::checkBool($var);
        $this->landingPageWithProxy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .core.PluginUsageType usageTypes = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUsageTypes()
    {
        return $this->usageTypes;
    }

    /**
     * Generated from protobuf field <code>repeated .core.PluginUsageType usageTypes = 7;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUsageTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Zaly\Proto\Core\PluginUsageType::class);
        $this->usageTypes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.core.PluginLoadingType loadingType = 8;</code>
     * @return int
     */
    public function getLoadingType()
    {
        return $this->loadingType;
    }

    /**
     * Generated from protobuf field <code>.core.PluginLoadingType loadingType = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setLoadingType($var)
    {
        GPBUtil::checkEnum($var, \Zaly\Proto\Core\PluginLoadingType::class);
        $this->loadingType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.core.PluginPermissionType permissionType = 9;</code>
     * @return int
     */
    public function getPermissionType()
    {
        return $this->permissionType;
    }

    /**
     * Generated from protobuf field <code>.core.PluginPermissionType permissionType = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setPermissionType($var)
    {
        GPBUtil::checkEnum($var, \Zaly\Proto\Core\PluginPermissionType::class);
        $this->permissionType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string userSessionId = 10;</code>
     * @return string
     */
    public function getUserSessionId()
    {
        return $this->userSessionId;
    }

    /**
     * Generated from protobuf field <code>string userSessionId = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setUserSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->userSessionId = $var;

        return $this;
    }

    /**
     *小程序管理url
     *
     * Generated from protobuf field <code>string adminPageUrl = 11;</code>
     * @return string
     */
    public function getAdminPageUrl()
    {
        return $this->adminPageUrl;
    }

    /**
     *小程序管理url
     *
     * Generated from protobuf field <code>string adminPageUrl = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setAdminPageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->adminPageUrl = $var;

        return $this;
    }

}

