<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/plugin.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\PluginPermissionType</code>
 */
class PluginPermissionType
{
    /**
     * Generated from protobuf enum <code>PluginPermissionAdminOnly = 0;</code>
     */
    const PluginPermissionAdminOnly = 0;
    /**
     * Generated from protobuf enum <code>PluginPermissionAll = 1;</code>
     */
    const PluginPermissionAll = 1;
    /**
     * Generated from protobuf enum <code>PluginPermissionGroupMaster = 2;</code>
     */
    const PluginPermissionGroupMaster = 2;
}

