<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/plugin.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\PluginUsageType</code>
 */
class PluginUsageType
{
    /**
     * if user give usageType equal 0, we will return all plugin  except usageType=0 
     *
     * Generated from protobuf enum <code>PluginUsageNone = 0;</code>
     */
    const PluginUsageNone = 0;
    /**
     * Generated from protobuf enum <code>PluginUsageIndex = 1;</code>
     */
    const PluginUsageIndex = 1;
    /**
     * Generated from protobuf enum <code>PluginUsageLogin = 2;</code>
     */
    const PluginUsageLogin = 2;
    /**
     * Generated from protobuf enum <code>PluginUsageU2Message = 3;</code>
     */
    const PluginUsageU2Message = 3;
    /**
     * Generated from protobuf enum <code>PluginUsageTmpMessage = 4;</code>
     */
    const PluginUsageTmpMessage = 4;
    /**
     * Generated from protobuf enum <code>PluginUsageGroupMessage = 5;</code>
     */
    const PluginUsageGroupMessage = 5;
    /**
     * Generated from protobuf enum <code>PluginUsageAccountSafe = 6;</code>
     */
    const PluginUsageAccountSafe = 6;
}

