<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/site.proto

namespace Zaly\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Publicly available configurations
 *
 * Generated from protobuf message <code>core.PublicSiteConfig</code>
 */
class PublicSiteConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string logo = 2;</code>
     */
    private $logo = '';
    /**
     * json array, [A, B, C]
     *
     * Generated from protobuf field <code>string masters = 3;</code>
     */
    private $masters = '';
    /**
     * Generated from protobuf field <code>string serverAddressForApi = 4;</code>
     */
    private $serverAddressForApi = '';
    /**
     * Generated from protobuf field <code>string serverAddressForIM = 5;</code>
     */
    private $serverAddressForIM = '';
    /**
     * Generated from protobuf field <code>bool enableCreateGroup = 6;</code>
     */
    private $enableCreateGroup = false;
    /**
     * Generated from protobuf field <code>bool enableAddFriend = 7;</code>
     */
    private $enableAddFriend = false;
    /**
     * Generated from protobuf field <code>bool enableTmpChat = 8;</code>
     */
    private $enableTmpChat = false;
    /**
     * Generated from protobuf field <code>bool enableInvitationCode = 9;</code>
     */
    private $enableInvitationCode = false;
    /**
     * Generated from protobuf field <code>bool enableRealName = 10;</code>
     */
    private $enableRealName = false;
    /**
     * Generated from protobuf field <code>int32 loginPluginId = 11;</code>
     */
    private $loginPluginId = 0;
    /**
     * Generated from protobuf field <code>int32 accountSafePluginId = 12;</code>
     */
    private $accountSafePluginId = 0;
    /**
     * Generated from protobuf field <code>bool enableWidgetWeb = 13;</code>
     */
    private $enableWidgetWeb = false;
    /**
     *pem instead of Base64，only use Base64 name
     *
     * Generated from protobuf field <code>string siteIdPubkBase64 = 14;</code>
     */
    private $siteIdPubkBase64 = '';
    /**
     * Generated from protobuf field <code>.core.Version version = 15;</code>
     */
    private $version = null;
    /**
     *replace Version=15 in new version >=1.1.3
     *
     * Generated from protobuf field <code>int32 versionCode = 16;</code>
     */
    private $versionCode = 0;
    /**
     *site administrators,need to replace masters,contains site owner & managers
     *
     * Generated from protobuf field <code>repeated string administrators = 17;</code>
     */
    private $administrators;
    /**
     * 1:Home 2:Chats 3:Contacts 4:Me
     *
     * Generated from protobuf field <code>.core.FrontPage frontPage = 18;</code>
     */
    private $frontPage = 0;
    /**
     *false:show home page ,true hidden home page
     *
     * Generated from protobuf field <code>bool hiddenHomePage = 19;</code>
     */
    private $hiddenHomePage = false;
    /**
     *true : show watermark ,false: hidden water mark(default)
     *
     * Generated from protobuf field <code>bool openWaterMark = 20;</code>
     */
    private $openWaterMark = false;

    public function __construct() {
        \GPBMetadata\Core\Site::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string logo = 2;</code>
     * @return string
     */
    public function getLogo()
    {
        return $this->logo;
    }

    /**
     * Generated from protobuf field <code>string logo = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLogo($var)
    {
        GPBUtil::checkString($var, True);
        $this->logo = $var;

        return $this;
    }

    /**
     * json array, [A, B, C]
     *
     * Generated from protobuf field <code>string masters = 3;</code>
     * @return string
     */
    public function getMasters()
    {
        return $this->masters;
    }

    /**
     * json array, [A, B, C]
     *
     * Generated from protobuf field <code>string masters = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMasters($var)
    {
        GPBUtil::checkString($var, True);
        $this->masters = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string serverAddressForApi = 4;</code>
     * @return string
     */
    public function getServerAddressForApi()
    {
        return $this->serverAddressForApi;
    }

    /**
     * Generated from protobuf field <code>string serverAddressForApi = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setServerAddressForApi($var)
    {
        GPBUtil::checkString($var, True);
        $this->serverAddressForApi = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string serverAddressForIM = 5;</code>
     * @return string
     */
    public function getServerAddressForIM()
    {
        return $this->serverAddressForIM;
    }

    /**
     * Generated from protobuf field <code>string serverAddressForIM = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setServerAddressForIM($var)
    {
        GPBUtil::checkString($var, True);
        $this->serverAddressForIM = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enableCreateGroup = 6;</code>
     * @return bool
     */
    public function getEnableCreateGroup()
    {
        return $this->enableCreateGroup;
    }

    /**
     * Generated from protobuf field <code>bool enableCreateGroup = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableCreateGroup($var)
    {
        GPBUtil::checkBool($var);
        $this->enableCreateGroup = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enableAddFriend = 7;</code>
     * @return bool
     */
    public function getEnableAddFriend()
    {
        return $this->enableAddFriend;
    }

    /**
     * Generated from protobuf field <code>bool enableAddFriend = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableAddFriend($var)
    {
        GPBUtil::checkBool($var);
        $this->enableAddFriend = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enableTmpChat = 8;</code>
     * @return bool
     */
    public function getEnableTmpChat()
    {
        return $this->enableTmpChat;
    }

    /**
     * Generated from protobuf field <code>bool enableTmpChat = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableTmpChat($var)
    {
        GPBUtil::checkBool($var);
        $this->enableTmpChat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enableInvitationCode = 9;</code>
     * @return bool
     */
    public function getEnableInvitationCode()
    {
        return $this->enableInvitationCode;
    }

    /**
     * Generated from protobuf field <code>bool enableInvitationCode = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableInvitationCode($var)
    {
        GPBUtil::checkBool($var);
        $this->enableInvitationCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enableRealName = 10;</code>
     * @return bool
     */
    public function getEnableRealName()
    {
        return $this->enableRealName;
    }

    /**
     * Generated from protobuf field <code>bool enableRealName = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableRealName($var)
    {
        GPBUtil::checkBool($var);
        $this->enableRealName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 loginPluginId = 11;</code>
     * @return int
     */
    public function getLoginPluginId()
    {
        return $this->loginPluginId;
    }

    /**
     * Generated from protobuf field <code>int32 loginPluginId = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setLoginPluginId($var)
    {
        GPBUtil::checkInt32($var);
        $this->loginPluginId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 accountSafePluginId = 12;</code>
     * @return int
     */
    public function getAccountSafePluginId()
    {
        return $this->accountSafePluginId;
    }

    /**
     * Generated from protobuf field <code>int32 accountSafePluginId = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setAccountSafePluginId($var)
    {
        GPBUtil::checkInt32($var);
        $this->accountSafePluginId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enableWidgetWeb = 13;</code>
     * @return bool
     */
    public function getEnableWidgetWeb()
    {
        return $this->enableWidgetWeb;
    }

    /**
     * Generated from protobuf field <code>bool enableWidgetWeb = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableWidgetWeb($var)
    {
        GPBUtil::checkBool($var);
        $this->enableWidgetWeb = $var;

        return $this;
    }

    /**
     *pem instead of Base64，only use Base64 name
     *
     * Generated from protobuf field <code>string siteIdPubkBase64 = 14;</code>
     * @return string
     */
    public function getSiteIdPubkBase64()
    {
        return $this->siteIdPubkBase64;
    }

    /**
     *pem instead of Base64，only use Base64 name
     *
     * Generated from protobuf field <code>string siteIdPubkBase64 = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteIdPubkBase64($var)
    {
        GPBUtil::checkString($var, True);
        $this->siteIdPubkBase64 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.core.Version version = 15;</code>
     * @return \Zaly\Proto\Core\Version
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>.core.Version version = 15;</code>
     * @param \Zaly\Proto\Core\Version $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkMessage($var, \Zaly\Proto\Core\Version::class);
        $this->version = $var;

        return $this;
    }

    /**
     *replace Version=15 in new version >=1.1.3
     *
     * Generated from protobuf field <code>int32 versionCode = 16;</code>
     * @return int
     */
    public function getVersionCode()
    {
        return $this->versionCode;
    }

    /**
     *replace Version=15 in new version >=1.1.3
     *
     * Generated from protobuf field <code>int32 versionCode = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setVersionCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->versionCode = $var;

        return $this;
    }

    /**
     *site administrators,need to replace masters,contains site owner & managers
     *
     * Generated from protobuf field <code>repeated string administrators = 17;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAdministrators()
    {
        return $this->administrators;
    }

    /**
     *site administrators,need to replace masters,contains site owner & managers
     *
     * Generated from protobuf field <code>repeated string administrators = 17;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAdministrators($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->administrators = $arr;

        return $this;
    }

    /**
     * 1:Home 2:Chats 3:Contacts 4:Me
     *
     * Generated from protobuf field <code>.core.FrontPage frontPage = 18;</code>
     * @return int
     */
    public function getFrontPage()
    {
        return $this->frontPage;
    }

    /**
     * 1:Home 2:Chats 3:Contacts 4:Me
     *
     * Generated from protobuf field <code>.core.FrontPage frontPage = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setFrontPage($var)
    {
        GPBUtil::checkEnum($var, \Zaly\Proto\Core\FrontPage::class);
        $this->frontPage = $var;

        return $this;
    }

    /**
     *false:show home page ,true hidden home page
     *
     * Generated from protobuf field <code>bool hiddenHomePage = 19;</code>
     * @return bool
     */
    public function getHiddenHomePage()
    {
        return $this->hiddenHomePage;
    }

    /**
     *false:show home page ,true hidden home page
     *
     * Generated from protobuf field <code>bool hiddenHomePage = 19;</code>
     * @param bool $var
     * @return $this
     */
    public function setHiddenHomePage($var)
    {
        GPBUtil::checkBool($var);
        $this->hiddenHomePage = $var;

        return $this;
    }

    /**
     *true : show watermark ,false: hidden water mark(default)
     *
     * Generated from protobuf field <code>bool openWaterMark = 20;</code>
     * @return bool
     */
    public function getOpenWaterMark()
    {
        return $this->openWaterMark;
    }

    /**
     *true : show watermark ,false: hidden water mark(default)
     *
     * Generated from protobuf field <code>bool openWaterMark = 20;</code>
     * @param bool $var
     * @return $this
     */
    public function setOpenWaterMark($var)
    {
        GPBUtil::checkBool($var);
        $this->openWaterMark = $var;

        return $this;
    }

}

