<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/user.proto

namespace Zaly\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>core.PublicUserProfile</code>
 */
class PublicUserProfile extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string userId = 1;</code>
     */
    private $userId = '';
    /**
     * Generated from protobuf field <code>string loginName = 2;</code>
     */
    private $loginName = '';
    /**
     * nickname or alias nickname
     *
     * Generated from protobuf field <code>string nickname = 3;</code>
     */
    private $nickname = '';
    /**
     * Generated from protobuf field <code>string nicknameInLatin = 4;</code>
     */
    private $nicknameInLatin = '';
    /**
     * Generated from protobuf field <code>string avatar = 5;</code>
     */
    private $avatar = '';
    /**
     * Generated from protobuf field <code>.core.UserAvailableType availableType = 6;</code>
     */
    private $availableType = 0;
    /**
     * Generated from protobuf field <code>string realNickname = 7;</code>
     */
    private $realNickname = '';
    /**
     * Generated from protobuf field <code>string loginPluginId = 8;</code>
     */
    private $loginPluginId = '';

    public function __construct() {
        \GPBMetadata\Core\User::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string userId = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Generated from protobuf field <code>string userId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->userId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string loginName = 2;</code>
     * @return string
     */
    public function getLoginName()
    {
        return $this->loginName;
    }

    /**
     * Generated from protobuf field <code>string loginName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLoginName($var)
    {
        GPBUtil::checkString($var, True);
        $this->loginName = $var;

        return $this;
    }

    /**
     * nickname or alias nickname
     *
     * Generated from protobuf field <code>string nickname = 3;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     * nickname or alias nickname
     *
     * Generated from protobuf field <code>string nickname = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nicknameInLatin = 4;</code>
     * @return string
     */
    public function getNicknameInLatin()
    {
        return $this->nicknameInLatin;
    }

    /**
     * Generated from protobuf field <code>string nicknameInLatin = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNicknameInLatin($var)
    {
        GPBUtil::checkString($var, True);
        $this->nicknameInLatin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string avatar = 5;</code>
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * Generated from protobuf field <code>string avatar = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->avatar = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.core.UserAvailableType availableType = 6;</code>
     * @return int
     */
    public function getAvailableType()
    {
        return $this->availableType;
    }

    /**
     * Generated from protobuf field <code>.core.UserAvailableType availableType = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setAvailableType($var)
    {
        GPBUtil::checkEnum($var, \Zaly\Proto\Core\UserAvailableType::class);
        $this->availableType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string realNickname = 7;</code>
     * @return string
     */
    public function getRealNickname()
    {
        return $this->realNickname;
    }

    /**
     * Generated from protobuf field <code>string realNickname = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setRealNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->realNickname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string loginPluginId = 8;</code>
     * @return string
     */
    public function getLoginPluginId()
    {
        return $this->loginPluginId;
    }

    /**
     * Generated from protobuf field <code>string loginPluginId = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setLoginPluginId($var)
    {
        GPBUtil::checkString($var, True);
        $this->loginPluginId = $var;

        return $this;
    }

}

