<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/site.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\PushType</code>
 */
class PushType
{
    /**
     * Generated from protobuf enum <code>PushDisabled = 0;</code>
     */
    const PushDisabled = 0;
    /**
     * Generated from protobuf enum <code>PushNotificationOnly = 1;</code>
     */
    const PushNotificationOnly = 1;
    /**
     * Generated from protobuf enum <code>PushWithMessageContent = 2;</code>
     */
    const PushWithMessageContent = 2;
}

