<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/message.proto

namespace Zaly\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>core.RecallMessage</code>
 */
class RecallMessage extends \Google\Protobuf\Internal\Message
{
    /**
     *recall message msgId
     *
     * Generated from protobuf field <code>string msgId = 1;</code>
     */
    private $msgId = '';
    /**
     *recall text,"sam recall a message"
     *
     * Generated from protobuf field <code>string text = 2;</code>
     */
    private $text = '';

    public function __construct() {
        \GPBMetadata\Core\Message::initOnce();
        parent::__construct();
    }

    /**
     *recall message msgId
     *
     * Generated from protobuf field <code>string msgId = 1;</code>
     * @return string
     */
    public function getMsgId()
    {
        return $this->msgId;
    }

    /**
     *recall message msgId
     *
     * Generated from protobuf field <code>string msgId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkString($var, True);
        $this->msgId = $var;

        return $this;
    }

    /**
     *recall text,"sam recall a message"
     *
     * Generated from protobuf field <code>string text = 2;</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     *recall text,"sam recall a message"
     *
     * Generated from protobuf field <code>string text = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;

        return $this;
    }

}

