<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/message.proto

namespace Zaly\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>core.StatusMessage</code>
 */
class StatusMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string msgId = 1;</code>
     */
    private $msgId = '';
    /**
     * Generated from protobuf field <code>.core.MessageStatus status = 2;</code>
     */
    private $status = 0;
    /**
     * whether this is a request.
     *
     * Generated from protobuf field <code>bool isReq = 3;</code>
     */
    private $isReq = false;

    public function __construct() {
        \GPBMetadata\Core\Message::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string msgId = 1;</code>
     * @return string
     */
    public function getMsgId()
    {
        return $this->msgId;
    }

    /**
     * Generated from protobuf field <code>string msgId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkString($var, True);
        $this->msgId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.core.MessageStatus status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.core.MessageStatus status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Zaly\Proto\Core\MessageStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * whether this is a request.
     *
     * Generated from protobuf field <code>bool isReq = 3;</code>
     * @return bool
     */
    public function getIsReq()
    {
        return $this->isReq;
    }

    /**
     * whether this is a request.
     *
     * Generated from protobuf field <code>bool isReq = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsReq($var)
    {
        GPBUtil::checkBool($var);
        $this->isReq = $var;

        return $this;
    }

}

