<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/message.proto

namespace Zaly\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *    bool hasNews = 1;
 *
 * Generated from protobuf message <code>core.SyncEndMessage</code>
 */
class SyncEndMessage extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Core\Message::initOnce();
        parent::__construct();
    }

}

