<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/net.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\UserClientLangType</code>
 */
class UserClientLangType
{
    /**
     * Generated from protobuf enum <code>UserClientLangEN = 0;</code>
     */
    const UserClientLangEN = 0;
    /**
     * Generated from protobuf enum <code>UserClientLangZH = 1;</code>
     */
    const UserClientLangZH = 1;
}

