<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/custom.proto

namespace Zaly\Proto\Core;

/**
 *
 * Protobuf enum <code>Core\UserCustomStatus</code>
 */
class UserCustomStatus
{
    /**
     * Generated from protobuf enum <code>UserCustomInvalid = 0;</code>
     */
    const UserCustomInvalid = 0;
    /**
     * Generated from protobuf enum <code>UserCustomNormal = 1;</code>
     */
    const UserCustomNormal = 1;
    /**
     * Generated from protobuf enum <code>UserCustomRegisterRequired = 2;</code>
     */
    const UserCustomRegisterRequired = 2;
}

