<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/net.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\UserClientType</code>
 */
class UserClientType
{
    /**
     * Generated from protobuf enum <code>UserClientMobileInvalid = 0;</code>
     */
    const UserClientMobileInvalid = 0;
    /**
     * Generated from protobuf enum <code>UserClientMobileApp = 1;</code>
     */
    const UserClientMobileApp = 1;
    /**
     * Generated from protobuf enum <code>UserClientWeb = 2;</code>
     */
    const UserClientWeb = 2;
}

