<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/user.proto

namespace Zaly\Proto\Core;

/**
 * Protobuf enum <code>Core\UserAvailableType</code>
 */
class UserAvailableType
{
    /**
     * Generated from protobuf enum <code>UserAvailableInvalid = 0;</code>
     */
    const UserAvailableInvalid = 0;
    /**
     * Generated from protobuf enum <code>UserAvailableNormal = 1;</code>
     */
    const UserAvailableNormal = 1;
    /**
     * Generated from protobuf enum <code>UserAvailableBlocked = 2;</code>
     */
    const UserAvailableBlocked = 2;
    /**
     * Generated from protobuf enum <code>UserAvailableGuest = 3;</code>
     */
    const UserAvailableGuest = 3;
}

