<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/site.proto

namespace Zaly\Proto\Core;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>core.Version</code>
 */
class Version extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 first = 1;</code>
     */
    private $first = 0;
    /**
     * Generated from protobuf field <code>int32 second = 2;</code>
     */
    private $second = 0;
    /**
     * Generated from protobuf field <code>int32 third = 3;</code>
     */
    private $third = 0;
    /**
     * proto-version
     *
     * Generated from protobuf field <code>int32 proto = 4;</code>
     */
    private $proto = 0;

    public function __construct() {
        \GPBMetadata\Core\Site::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 first = 1;</code>
     * @return int
     */
    public function getFirst()
    {
        return $this->first;
    }

    /**
     * Generated from protobuf field <code>int32 first = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFirst($var)
    {
        GPBUtil::checkInt32($var);
        $this->first = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 second = 2;</code>
     * @return int
     */
    public function getSecond()
    {
        return $this->second;
    }

    /**
     * Generated from protobuf field <code>int32 second = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSecond($var)
    {
        GPBUtil::checkInt32($var);
        $this->second = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 third = 3;</code>
     * @return int
     */
    public function getThird()
    {
        return $this->third;
    }

    /**
     * Generated from protobuf field <code>int32 third = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setThird($var)
    {
        GPBUtil::checkInt32($var);
        $this->third = $var;

        return $this;
    }

    /**
     * proto-version
     *
     * Generated from protobuf field <code>int32 proto = 4;</code>
     * @return int
     */
    public function getProto()
    {
        return $this->proto;
    }

    /**
     * proto-version
     *
     * Generated from protobuf field <code>int32 proto = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setProto($var)
    {
        GPBUtil::checkInt32($var);
        $this->proto = $var;

        return $this;
    }

}

