<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gw_socket_write.proto

namespace Zaly\Proto\Gateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * error:
 *      error.offline    the sockeid if offline.
 *
 * Generated from protobuf message <code>gateway.GwSocketWriteRequest</code>
 */
class GwSocketWriteRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .gateway.GwSocketWritePackage packages = 1;</code>
     */
    private $packages;

    public function __construct() {
        \GPBMetadata\Gateway\GwSocketWrite::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .gateway.GwSocketWritePackage packages = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPackages()
    {
        return $this->packages;
    }

    /**
     * Generated from protobuf field <code>repeated .gateway.GwSocketWritePackage packages = 1;</code>
     * @param \Zaly\Proto\Gateway\GwSocketWritePackage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPackages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zaly\Proto\Gateway\GwSocketWritePackage::class);
        $this->packages = $arr;

        return $this;
    }

}

