<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gw_socket_close.proto

namespace Zaly\Proto\Gateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gateway.GwSocketCloseResponse</code>
 */
class GwSocketCloseResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Gateway\GwSocketClose::initOnce();
        parent::__construct();
    }

}

