<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/duckchat_group_checkMember.proto

namespace GPBMetadata\Plugin;

class DuckchatGroupCheckMember
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Group::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af9010a27706c7567696e2f6475636b636861745f67726f75705f636865" .
            "636b4d656d6265722e70726f746f1206706c7567696e22420a1f4475636b" .
            "4368617447726f7570436865636b4d656d62657252657175657374120f0a" .
            "0767726f75704964180120012809120e0a06757365724964180220012809" .
            "224d0a204475636b4368617447726f7570436865636b4d656d6265725265" .
            "73706f6e736512290a0a6d656d6265725479706518012001280e32152e63" .
            "6f72652e47726f75704d656d62657254797065422b0a15636f6d2e7a616c" .
            "792e70726f746f2e706c7567696eca02115a616c795c50726f746f5c506c" .
            "7567696e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

