<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/duckchat_message_send.proto

namespace GPBMetadata\Plugin;

class DuckchatMessageSend
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Message::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0abe010a22706c7567696e2f6475636b636861745f6d6573736167655f73" .
            "656e642e70726f746f1206706c7567696e223c0a1a4475636b436861744d" .
            "65737361676553656e6452657175657374121e0a076d6573736167651801" .
            "2001280b320d2e636f72652e4d657373616765221d0a1b4475636b436861" .
            "744d65737361676553656e64526573706f6e7365422b0a15636f6d2e7a61" .
            "6c792e70726f746f2e706c7567696eca02115a616c795c50726f746f5c50" .
            "6c7567696e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

