<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/duckchat_user_relation.proto

namespace GPBMetadata\Plugin;

class DuckchatUserRelation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af9010a23706c7567696e2f6475636b636861745f757365725f72656c61" .
            "74696f6e2e70726f746f1206706c7567696e22450a1b4475636b43686174" .
            "5573657252656c6174696f6e52657175657374120e0a0675736572496418" .
            "012001280912160a0e6f70706f7369746555736572496418022001280922" .
            "4e0a1c4475636b436861745573657252656c6174696f6e526573706f6e73" .
            "65122e0a0c72656c6174696f6e5479706518012001280e32182e636f7265" .
            "2e467269656e6452656c6174696f6e54797065422b0a15636f6d2e7a616c" .
            "792e70726f746f2e706c7567696eca02115a616c795c50726f746f5c506c" .
            "7567696e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

