<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/duckchat_session_clear.proto

namespace GPBMetadata\Plugin;

class DuckchatSessionClear
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab1010a23706c7567696e2f6475636b636861745f73657373696f6e5f63" .
            "6c6561722e70726f746f1206706c7567696e222d0a1b4475636b43686174" .
            "53657373696f6e436c65617252657175657374120e0a0675736572496418" .
            "0120012809221e0a1c4475636b4368617453657373696f6e436c65617252" .
            "6573706f6e7365422b0a15636f6d2e7a616c792e70726f746f2e706c7567" .
            "696eca02115a616c795c50726f746f5c506c7567696e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

