<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client/im_stc_pong.proto

namespace GPBMetadata\Client;

class ImStcPong
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aae010a18636c69656e742f696d5f7374635f706f6e672e70726f746f12" .
            "06636c69656e7422220a10496d537463506f6e6752657175657374120e0a" .
            "0672616e646f6d180120012809425e0a15636f6d2e7a616c792e70726f74" .
            "6f2e636c69656e745a316769746875622e636f6d2f6475636b636861742f" .
            "6475636b636861742d676174657761792f70726f746f2f636c69656e74ca" .
            "02115a616c795c50726f746f5c436c69656e74620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

