<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client/im_stc_news.proto

namespace GPBMetadata\Client;

class ImStcNews
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9e010a18636c69656e742f696d5f7374635f6e6577732e70726f746f12" .
            "06636c69656e7422120a10496d5374634e65777352657175657374425e0a" .
            "15636f6d2e7a616c792e70726f746f2e636c69656e745a31676974687562" .
            "2e636f6d2f6475636b636861742f6475636b636861742d67617465776179" .
            "2f70726f746f2f636c69656e74ca02115a616c795c50726f746f5c436c69" .
            "656e74620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

