<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client/im_stc_message.proto

namespace GPBMetadata\Client;

class ImStcMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Message::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac1010a1b636c69656e742f696d5f7374635f6d6573736167652e70726f" .
            "746f1206636c69656e7422320a13496d5374634d65737361676552657175" .
            "657374121b0a046c69737418012003280b320d2e636f72652e4d65737361" .
            "6765425e0a15636f6d2e7a616c792e70726f746f2e636c69656e745a3167" .
            "69746875622e636f6d2f6475636b636861742f6475636b636861742d6761" .
            "74657761792f70726f746f2f636c69656e74ca02115a616c795c50726f74" .
            "6f5c436c69656e74620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

