<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_platform_check.proto

namespace Zaly\Proto\Platform;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: platform.api.platform.check
 *
 * Generated from protobuf message <code>platform.ApiPlatformCheckRequest</code>
 */
class ApiPlatformCheckRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string phoneCountryCode = 1;</code>
     */
    private $phoneCountryCode = '';
    /**
     * Generated from protobuf field <code>string phoneNumber = 2;</code>
     */
    private $phoneNumber = '';

    public function __construct() {
        \GPBMetadata\Platform\ApiPlatformCheck::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string phoneCountryCode = 1;</code>
     * @return string
     */
    public function getPhoneCountryCode()
    {
        return $this->phoneCountryCode;
    }

    /**
     * Generated from protobuf field <code>string phoneCountryCode = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneCountryCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->phoneCountryCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phoneNumber = 2;</code>
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->phoneNumber;
    }

    /**
     * Generated from protobuf field <code>string phoneNumber = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->phoneNumber = $var;

        return $this;
    }

}

