<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_push_cancel.proto

namespace Zaly\Proto\Platform;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: platform.api.push.auth
 *
 * Generated from protobuf message <code>platform.ApiPushCancelRequest</code>
 */
class ApiPushCancelRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sitePubkPem = 1;</code>
     */
    private $sitePubkPem = '';
    /**
     * Generated from protobuf field <code>string devicePubkPem = 2;</code>
     */
    private $devicePubkPem = '';
    /**
     * Generated from protobuf field <code>string timestampSeconds = 3;</code>
     */
    private $timestampSeconds = '';
    /**
     * Generated from protobuf field <code>string signTimestamp = 4;</code>
     */
    private $signTimestamp = '';

    public function __construct() {
        \GPBMetadata\Platform\ApiPushCancel::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string sitePubkPem = 1;</code>
     * @return string
     */
    public function getSitePubkPem()
    {
        return $this->sitePubkPem;
    }

    /**
     * Generated from protobuf field <code>string sitePubkPem = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSitePubkPem($var)
    {
        GPBUtil::checkString($var, True);
        $this->sitePubkPem = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string devicePubkPem = 2;</code>
     * @return string
     */
    public function getDevicePubkPem()
    {
        return $this->devicePubkPem;
    }

    /**
     * Generated from protobuf field <code>string devicePubkPem = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDevicePubkPem($var)
    {
        GPBUtil::checkString($var, True);
        $this->devicePubkPem = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string timestampSeconds = 3;</code>
     * @return string
     */
    public function getTimestampSeconds()
    {
        return $this->timestampSeconds;
    }

    /**
     * Generated from protobuf field <code>string timestampSeconds = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTimestampSeconds($var)
    {
        GPBUtil::checkString($var, True);
        $this->timestampSeconds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string signTimestamp = 4;</code>
     * @return string
     */
    public function getSignTimestamp()
    {
        return $this->signTimestamp;
    }

    /**
     * Generated from protobuf field <code>string signTimestamp = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSignTimestamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->signTimestamp = $var;

        return $this;
    }

}

