<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_push_auth.proto

namespace Zaly\Proto\Platform;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: platform/api.push.auth
 *
 * Generated from protobuf message <code>platform.ApiPushAuthRequest</code>
 */
class ApiPushAuthRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sitePubkPem = 1;</code>
     */
    private $sitePubkPem = '';
    /**
     * Generated from protobuf field <code>string siteAddressApi = 2;</code>
     */
    private $siteAddressApi = '';
    /**
     * Generated from protobuf field <code>string siteName = 3;</code>
     */
    private $siteName = '';
    /**
     * Generated from protobuf field <code>string pushToken = 4;</code>
     */
    private $pushToken = '';
    /**
     * Generated from protobuf field <code>.platform.PushTokenType pushTokenType = 5;</code>
     */
    private $pushTokenType = 0;
    /**
     * Generated from protobuf field <code>string devicePubkPem = 6;</code>
     */
    private $devicePubkPem = '';
    /**
     * = string(timestamp unit: seconds)
     *
     * Generated from protobuf field <code>string timestampSeconds = 7;</code>
     */
    private $timestampSeconds = '';
    /**
     * sign(timestampSeconds)
     *
     * Generated from protobuf field <code>string signTimestampBase64 = 8;</code>
     */
    private $signTimestampBase64 = '';
    /**
     * sign(sitePubkPem)
     *
     * Generated from protobuf field <code>string signSitePubkPemBase64 = 9;</code>
     */
    private $signSitePubkPemBase64 = '';
    /**
     * site userId
     *
     * Generated from protobuf field <code>string siteUserId = 10;</code>
     */
    private $siteUserId = '';

    public function __construct() {
        \GPBMetadata\Platform\ApiPushAuth::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string sitePubkPem = 1;</code>
     * @return string
     */
    public function getSitePubkPem()
    {
        return $this->sitePubkPem;
    }

    /**
     * Generated from protobuf field <code>string sitePubkPem = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSitePubkPem($var)
    {
        GPBUtil::checkString($var, True);
        $this->sitePubkPem = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string siteAddressApi = 2;</code>
     * @return string
     */
    public function getSiteAddressApi()
    {
        return $this->siteAddressApi;
    }

    /**
     * Generated from protobuf field <code>string siteAddressApi = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteAddressApi($var)
    {
        GPBUtil::checkString($var, True);
        $this->siteAddressApi = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string siteName = 3;</code>
     * @return string
     */
    public function getSiteName()
    {
        return $this->siteName;
    }

    /**
     * Generated from protobuf field <code>string siteName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteName($var)
    {
        GPBUtil::checkString($var, True);
        $this->siteName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pushToken = 4;</code>
     * @return string
     */
    public function getPushToken()
    {
        return $this->pushToken;
    }

    /**
     * Generated from protobuf field <code>string pushToken = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPushToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->pushToken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.platform.PushTokenType pushTokenType = 5;</code>
     * @return int
     */
    public function getPushTokenType()
    {
        return $this->pushTokenType;
    }

    /**
     * Generated from protobuf field <code>.platform.PushTokenType pushTokenType = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPushTokenType($var)
    {
        GPBUtil::checkEnum($var, \Zaly\Proto\Platform\PushTokenType::class);
        $this->pushTokenType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string devicePubkPem = 6;</code>
     * @return string
     */
    public function getDevicePubkPem()
    {
        return $this->devicePubkPem;
    }

    /**
     * Generated from protobuf field <code>string devicePubkPem = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDevicePubkPem($var)
    {
        GPBUtil::checkString($var, True);
        $this->devicePubkPem = $var;

        return $this;
    }

    /**
     * = string(timestamp unit: seconds)
     *
     * Generated from protobuf field <code>string timestampSeconds = 7;</code>
     * @return string
     */
    public function getTimestampSeconds()
    {
        return $this->timestampSeconds;
    }

    /**
     * = string(timestamp unit: seconds)
     *
     * Generated from protobuf field <code>string timestampSeconds = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTimestampSeconds($var)
    {
        GPBUtil::checkString($var, True);
        $this->timestampSeconds = $var;

        return $this;
    }

    /**
     * sign(timestampSeconds)
     *
     * Generated from protobuf field <code>string signTimestampBase64 = 8;</code>
     * @return string
     */
    public function getSignTimestampBase64()
    {
        return $this->signTimestampBase64;
    }

    /**
     * sign(timestampSeconds)
     *
     * Generated from protobuf field <code>string signTimestampBase64 = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setSignTimestampBase64($var)
    {
        GPBUtil::checkString($var, True);
        $this->signTimestampBase64 = $var;

        return $this;
    }

    /**
     * sign(sitePubkPem)
     *
     * Generated from protobuf field <code>string signSitePubkPemBase64 = 9;</code>
     * @return string
     */
    public function getSignSitePubkPemBase64()
    {
        return $this->signSitePubkPemBase64;
    }

    /**
     * sign(sitePubkPem)
     *
     * Generated from protobuf field <code>string signSitePubkPemBase64 = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setSignSitePubkPemBase64($var)
    {
        GPBUtil::checkString($var, True);
        $this->signSitePubkPemBase64 = $var;

        return $this;
    }

    /**
     * site userId
     *
     * Generated from protobuf field <code>string siteUserId = 10;</code>
     * @return string
     */
    public function getSiteUserId()
    {
        return $this->siteUserId;
    }

    /**
     * site userId
     *
     * Generated from protobuf field <code>string siteUserId = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->siteUserId = $var;

        return $this;
    }

}

