<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_push_payload.proto

namespace Zaly\Proto\Platform;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: api.push.payload
 * platform -> zaly-push
 *
 * Generated from protobuf message <code>platform.ApiPushPayloadRequest</code>
 */
class ApiPushPayloadRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .platform.Payload payloads = 1;</code>
     */
    private $payloads;

    public function __construct() {
        \GPBMetadata\Platform\ApiPushPayload::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .platform.Payload payloads = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPayloads()
    {
        return $this->payloads;
    }

    /**
     * Generated from protobuf field <code>repeated .platform.Payload payloads = 1;</code>
     * @param \Zaly\Proto\Platform\Payload[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPayloads($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zaly\Proto\Platform\Payload::class);
        $this->payloads = $arr;

        return $this;
    }

}

