<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_site_mute.proto

namespace Zaly\Proto\Platform;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>platform.ApiSiteMuteResponse</code>
 */
class ApiSiteMuteResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Platform\ApiSiteMute::initOnce();
        parent::__construct();
    }

}

