<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_site_register.proto

namespace Zaly\Proto\Platform;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: platform.api.site.register
 *
 * Generated from protobuf message <code>platform.ApiSiteRegisterRequest</code>
 */
class ApiSiteRegisterRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string nickname = 1;</code>
     */
    private $nickname = '';
    /**
     * Generated from protobuf field <code>string invitationCode = 2;</code>
     */
    private $invitationCode = '';
    /**
     *does the user allow the platform to share his realname with the site that he is on. 
     *
     * Generated from protobuf field <code>bool allowShareRealname = 3;</code>
     */
    private $allowShareRealname = false;
    /**
     * Generated from protobuf field <code>string sitePubkPem = 4;</code>
     */
    private $sitePubkPem = '';

    public function __construct() {
        \GPBMetadata\Platform\ApiSiteRegister::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string nickname = 1;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     * Generated from protobuf field <code>string nickname = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string invitationCode = 2;</code>
     * @return string
     */
    public function getInvitationCode()
    {
        return $this->invitationCode;
    }

    /**
     * Generated from protobuf field <code>string invitationCode = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setInvitationCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->invitationCode = $var;

        return $this;
    }

    /**
     *does the user allow the platform to share his realname with the site that he is on. 
     *
     * Generated from protobuf field <code>bool allowShareRealname = 3;</code>
     * @return bool
     */
    public function getAllowShareRealname()
    {
        return $this->allowShareRealname;
    }

    /**
     *does the user allow the platform to share his realname with the site that he is on. 
     *
     * Generated from protobuf field <code>bool allowShareRealname = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setAllowShareRealname($var)
    {
        GPBUtil::checkBool($var);
        $this->allowShareRealname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sitePubkPem = 4;</code>
     * @return string
     */
    public function getSitePubkPem()
    {
        return $this->sitePubkPem;
    }

    /**
     * Generated from protobuf field <code>string sitePubkPem = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSitePubkPem($var)
    {
        GPBUtil::checkString($var, True);
        $this->sitePubkPem = $var;

        return $this;
    }

}

