<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_sms_verifyCode.proto

namespace Zaly\Proto\Platform;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>platform.ApiVerifyCodeResponse</code>
 */
class ApiVerifyCodeResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Platform\ApiSmsVerifyCode::initOnce();
        parent::__construct();
    }

}

