<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_sms_verifyCode.proto

namespace Zaly\Proto\Platform;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: platform.api.sms.verifyCode
 * error:
 *    error.phone  the phone number format is invalid.
 *
 * Generated from protobuf message <code>platform.ApiVerifyCodeRequest</code>
 */
class ApiVerifyCodeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string phoneCountryCode = 1;</code>
     */
    private $phoneCountryCode = '';
    /**
     * Generated from protobuf field <code>string phoneNumber = 2;</code>
     */
    private $phoneNumber = '';
    /**
     * Generated from protobuf field <code>.platform.SmsVerifyCodeType type = 3;</code>
     */
    private $type = 0;

    public function __construct() {
        \GPBMetadata\Platform\ApiSmsVerifyCode::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string phoneCountryCode = 1;</code>
     * @return string
     */
    public function getPhoneCountryCode()
    {
        return $this->phoneCountryCode;
    }

    /**
     * Generated from protobuf field <code>string phoneCountryCode = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneCountryCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->phoneCountryCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phoneNumber = 2;</code>
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->phoneNumber;
    }

    /**
     * Generated from protobuf field <code>string phoneNumber = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->phoneNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.platform.SmsVerifyCodeType type = 3;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.platform.SmsVerifyCodeType type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Zaly\Proto\Platform\SmsVerifyCodeType::class);
        $this->type = $var;

        return $this;
    }

}

