<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/common.proto

namespace Zaly\Proto\Platform;

/**
 *payload type
 *
 * Protobuf enum <code>Platform\PayloadType</code>
 */
class PayloadType
{
    /**
     * Generated from protobuf enum <code>UNKNOW_TYPE = 0;</code>
     */
    const UNKNOW_TYPE = 0;
    /**
     * Generated from protobuf enum <code>IOS = 1;</code>
     */
    const IOS = 1;
    /**
     * Generated from protobuf enum <code>ANDROID = 2;</code>
     */
    const ANDROID = 2;
    /**
     * Generated from protobuf enum <code>XIAOMI = 3;</code>
     */
    const XIAOMI = 3;
    /**
     * Generated from protobuf enum <code>HUAWEI = 4;</code>
     */
    const HUAWEI = 4;
    /**
     * Generated from protobuf enum <code>GCM = 5;</code>
     */
    const GCM = 5;
}

