<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/common.proto

namespace Zaly\Proto\Platform;

/**
 * Protobuf enum <code>Platform\PushTokenType</code>
 */
class PushTokenType
{
    /**
     * Generated from protobuf enum <code>pushTokenInvalid = 0;</code>
     */
    const pushTokenInvalid = 0;
    /**
     * Generated from protobuf enum <code>pushTokenIOS = 1;</code>
     */
    const pushTokenIOS = 1;
    /**
     * Generated from protobuf enum <code>pushTokenAndroid = 2;</code>
     */
    const pushTokenAndroid = 2;
    /**
     * Generated from protobuf enum <code>pushTokenXiaoMi = 3;</code>
     */
    const pushTokenXiaoMi = 3;
    /**
     * Generated from protobuf enum <code>pushTokenHuawei = 4;</code>
     */
    const pushTokenHuawei = 4;
    /**
     * Generated from protobuf enum <code>pushTokenGCM = 5;</code>
     */
    const pushTokenGCM = 5;
}

