<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/common.proto

namespace Zaly\Proto\Platform;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *------- push header && body -------
 *
 * Generated from protobuf message <code>platform.PushHeader</code>
 */
class PushHeader extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string siteAddress = 1;</code>
     */
    private $siteAddress = '';
    /**
     * Generated from protobuf field <code>string siteName = 2;</code>
     */
    private $siteName = '';
    /**
     * Generated from protobuf field <code>string sitePubkPemId = 3;</code>
     */
    private $sitePubkPemId = '';
    /**
     * string(timestamp unit: seconds)
     *
     * Generated from protobuf field <code>string timestampSeconds = 4;</code>
     */
    private $timestampSeconds = '';
    /**
     * Generated from protobuf field <code>string signTimestamp = 5;</code>
     */
    private $signTimestamp = '';

    public function __construct() {
        \GPBMetadata\Platform\Common::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string siteAddress = 1;</code>
     * @return string
     */
    public function getSiteAddress()
    {
        return $this->siteAddress;
    }

    /**
     * Generated from protobuf field <code>string siteAddress = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->siteAddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string siteName = 2;</code>
     * @return string
     */
    public function getSiteName()
    {
        return $this->siteName;
    }

    /**
     * Generated from protobuf field <code>string siteName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteName($var)
    {
        GPBUtil::checkString($var, True);
        $this->siteName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sitePubkPemId = 3;</code>
     * @return string
     */
    public function getSitePubkPemId()
    {
        return $this->sitePubkPemId;
    }

    /**
     * Generated from protobuf field <code>string sitePubkPemId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSitePubkPemId($var)
    {
        GPBUtil::checkString($var, True);
        $this->sitePubkPemId = $var;

        return $this;
    }

    /**
     * string(timestamp unit: seconds)
     *
     * Generated from protobuf field <code>string timestampSeconds = 4;</code>
     * @return string
     */
    public function getTimestampSeconds()
    {
        return $this->timestampSeconds;
    }

    /**
     * string(timestamp unit: seconds)
     *
     * Generated from protobuf field <code>string timestampSeconds = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTimestampSeconds($var)
    {
        GPBUtil::checkString($var, True);
        $this->timestampSeconds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string signTimestamp = 5;</code>
     * @return string
     */
    public function getSignTimestamp()
    {
        return $this->signTimestamp;
    }

    /**
     * Generated from protobuf field <code>string signTimestamp = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSignTimestamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->signTimestamp = $var;

        return $this;
    }

}

