<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_sms_verifyCode.proto

namespace Zaly\Proto\Platform;

/**
 * Protobuf enum <code>Platform\SmsVerifyCodeType</code>
 */
class SmsVerifyCodeType
{
    /**
     * Generated from protobuf enum <code>SmsVerifyCodeInvalid = 0;</code>
     */
    const SmsVerifyCodeInvalid = 0;
    /**
     * Generated from protobuf enum <code>SmsVerifyCodeLogin = 1;</code>
     */
    const SmsVerifyCodeLogin = 1;
}

